-- Auto-generated by event-sync on 2026-05-30
-- Scraped range: 2026-05-30 → 2026-06-20
-- Run manually in Supabase Dashboard → SQL Editor
-- Idempotent: ON CONFLICT (external_id) DO NOTHING skips duplicates
-- Requires migration 20260530_add_external_id.sql

DO $$
DECLARE
  team_id uuid := 'b864b6bf-4282-4644-ab8f-b17b661b7841';
BEGIN

-- VI Muestra de Cine español de Tenerife [lagenda:42403]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id) VALUES (
  gen_random_uuid(),
  'VI Muestra de Cine español de Tenerife',
  'VI Muestra de Cine Español con Julio Medem como protagonista en una edición que contará también con la actriz Aida Folch. Las películas que constituyen la muestra de este año son ''El Artista y la Modelo'' de Fernando Trueba, ''Tierra'' y ''Lucía y El Sexo'' (ambas escritas y dirigidas por Julio Medem). Más info y entradas online',
  28.463192, -16.306475,
  'Multicines Tenerife, Multicines Tenerife',
  'music',
  '2026-05-30 18:00:00+00',
  '2026-05-30 20:00:00+00',
  team_id, 'upcoming', 'lagenda:42403'
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['music'])
  FROM events WHERE external_id = 'lagenda:42403'
ON CONFLICT DO NOTHING;

-- Día de Canarias en Vilaflor de Chasna 2026 [lagenda:42404]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id) VALUES (
  gen_random_uuid(),
  'Día de Canarias en Vilaflor de Chasna 2026',
  'Jornada del Día de Canarias en Vilaflor de Chasna dedicada a la memoria, la tradición oral y los saberes populares del municipio. La programación incluye una exposición fotográfica, la proyección de un documental y la actuación musical de Caracolas con su propuesta de ''Matria''.',
  28.158776, -16.647281,
  'Vilaflor, Vilaflor',
  'music',
  '2026-05-30 18:00:00+00',
  '2026-05-30 20:00:00+00',
  team_id, 'upcoming', 'lagenda:42404'
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['music'])
  FROM events WHERE external_id = 'lagenda:42404'
ON CONFLICT DO NOTHING;

-- XXI Baile de Taifas de Granadilla de Abona [lagenda:42407]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id) VALUES (
  gen_random_uuid(),
  'XXI Baile de Taifas de Granadilla de Abona',
  'El evento reunirá a miles de personas en torno a 110 mesas en una noche marcada por la música popular, la gastronomía y las tradiciones. Aires de Abona, Viñático, Alisios del Sur, Guaydil del Sur, Sentir Sureño y La Parranda,pondrán la banda sonora a una velada dedicada a las raíces y costumbres canarias.',
  28.121900, -16.579800,
  'Granadilla Casco, Granadilla Casco',
  'music',
  '2026-05-30 18:00:00+00',
  '2026-05-30 20:00:00+00',
  team_id, 'upcoming', 'lagenda:42407'
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['music'])
  FROM events WHERE external_id = 'lagenda:42407'
ON CONFLICT DO NOTHING;

-- A raíz - La Laguna canta a Canarias [lagenda:42410]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id) VALUES (
  gen_random_uuid(),
  'A raíz - La Laguna canta a Canarias',
  'La Agrupación Folclórica El Moral y la Agrupación Folklórica Guantejina celebrarán el Día de Canarias con música y bailes tradicionales. Esta edición del proyecto A raíz, de la iniciativa municipal ''Mi barrio es cultura'', ha conmemorado esta festividad a lo largo de todo el mes de mayo.',
  28.485771, -16.315942,
  'La Laguna, La Laguna',
  'music',
  '2026-05-30 18:00:00+00',
  '2026-05-30 20:00:00+00',
  team_id, 'upcoming', 'lagenda:42410'
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['music'])
  FROM events WHERE external_id = 'lagenda:42410'
ON CONFLICT DO NOTHING;

-- ''¿Qué te dice esa naturaleza?'' [lagenda:42335]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id) VALUES (
  gen_random_uuid(),
  '''¿Qué te dice esa naturaleza?''',
  '''¿Qué te dice esa naturaleza?'', de Hong Sang-soo. El filme narra el primer encuentro de un joven con la familia de su novia, desvelando sus tensiones y secretos.',
  28.291600, -16.629100,
  'TEA Tenerife Espacio de las Artes, TEA Tenerife Espacio de las Artes',
  'music',
  '2026-05-30 18:00:00+00',
  '2026-05-30 20:00:00+00',
  team_id, 'upcoming', 'lagenda:42335'
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['music'])
  FROM events WHERE external_id = 'lagenda:42335'
ON CONFLICT DO NOTHING;

-- Día de Canarias 2026 - La Orotava [lagenda:42336]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id) VALUES (
  gen_random_uuid(),
  'Día de Canarias 2026 - La Orotava',
  'La Orotava celebra el Día de Canarias con actividades populares en conjunción con los eventos de sus fiestas patronales',
  28.389883, -16.523569,
  'La Orotava, La Orotava',
  'music',
  '2026-05-30 18:00:00+00',
  '2026-05-30 20:00:00+00',
  team_id, 'upcoming', 'lagenda:42336'
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['music'])
  FROM events WHERE external_id = 'lagenda:42336'
ON CONFLICT DO NOTHING;

-- FlorAguere 2026 [lagenda:42346]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id) VALUES (
  gen_random_uuid(),
  'FlorAguere 2026',
  'FlorAguere dedica su edición de 2026 al Arte Floral inspirado en las letras canarias. Cuenta con exposiciones de reconocidos artistas florales realizadas a partir de flora exclusiva de las islas y demostraciones de arte floral en vivo.',
  28.485798, -16.312900,
  'Convento Santo Domingo La Laguna, Convento Santo Domingo La Laguna',
  'music',
  '2026-05-30 18:00:00+00',
  '2026-05-30 20:00:00+00',
  team_id, 'upcoming', 'lagenda:42346'
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['music'])
  FROM events WHERE external_id = 'lagenda:42346'
ON CONFLICT DO NOTHING;

-- Día de Canarias 2026 en Los Realejos [lagenda:42348]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id) VALUES (
  gen_random_uuid(),
  'Día de Canarias 2026 en Los Realejos',
  'Festivales, bailes y la romería de San Isidro Labrador entre las actividades que Los Realejos celebra en conjunción con el Día de Canarias 2026',
  28.350311, -16.584952,
  'Los Realejos, Los Realejos',
  'music',
  '2026-05-30 18:00:00+00',
  '2026-05-30 20:00:00+00',
  team_id, 'upcoming', 'lagenda:42348'
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['music'])
  FROM events WHERE external_id = 'lagenda:42348'
ON CONFLICT DO NOTHING;

-- Día de Canarias 2026 en santa cruz de tenerife [lagenda:42349]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id) VALUES (
  gen_random_uuid(),
  'Día de Canarias 2026 en santa cruz de tenerife',
  'Actividades familiares y populares, actos institucionales y tradicionales, conciertos y ferias para celebrar el Día de Canarias 2026 durante dos jornadas en Santa Cruz de Tenerife',
  28.467178, -16.250784,
  'Santa Cruz, Santa Cruz',
  'music',
  '2026-05-30 18:00:00+00',
  '2026-05-30 20:00:00+00',
  team_id, 'upcoming', 'lagenda:42349'
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['music'])
  FROM events WHERE external_id = 'lagenda:42349'
ON CONFLICT DO NOTHING;

-- Día de Canarias 2026 en el C.C. Alcampo La Laguna [lagenda:42370]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id) VALUES (
  gen_random_uuid(),
  'Día de Canarias 2026 en el C.C. Alcampo La Laguna',
  'Actividades para celebrar con tradiciones el Día de Canarias con talleres de pintaderas con arcillas, pulseras, llaveros y actuación folclórica de Andares Isleños',
  28.485771, -16.315942,
  'La Laguna, La Laguna',
  'music',
  '2026-05-30 18:00:00+00',
  '2026-05-30 20:00:00+00',
  team_id, 'upcoming', 'lagenda:42370'
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['music'])
  FROM events WHERE external_id = 'lagenda:42370'
ON CONFLICT DO NOTHING;

-- Día de Canarias 2026 en el C.C.Meridiano [lagenda:42371]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id) VALUES (
  gen_random_uuid(),
  'Día de Canarias 2026 en el C.C.Meridiano',
  'El Centro Comercial Meridiano celebra el Día de Canarias 2026 por todo lo alto con ''Nos vamos de teneriferete'': dos días llenos de actividades, juegos y tradición',
  37.372751, -5.947118,
  'C.C. Meridiano, C.C. Meridiano',
  'music',
  '2026-05-30 18:00:00+00',
  '2026-05-30 20:00:00+00',
  team_id, 'upcoming', 'lagenda:42371'
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['music'])
  FROM events WHERE external_id = 'lagenda:42371'
ON CONFLICT DO NOTHING;

-- Jaleo en la Plaza - FICMEC 2026 [lagenda:42384]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id) VALUES (
  gen_random_uuid(),
  'Jaleo en la Plaza - FICMEC 2026',
  'El Festival Internacional de Cine Medioambiental de Canarias (FICMEC) ofrece en 2026 una ambiciosa propuesta que va más allá de la gran pantalla. Bajo el sello de ‘Jaleo en la Plaza’, el festival ha diseñado una completa programación cultural y familiar que llenará de vida los espacios públicos de Garachico e Icod de los Vinos',
  28.293578, -16.621447,
  'Tenerife, Tenerife',
  'music',
  '2026-05-30 18:00:00+00',
  '2026-05-30 20:00:00+00',
  team_id, 'upcoming', 'lagenda:42384'
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['music'])
  FROM events WHERE external_id = 'lagenda:42384'
ON CONFLICT DO NOTHING;

-- Bresh 2026 - Parque Marítimo [lagenda:42286]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id) VALUES (
  gen_random_uuid(),
  'Bresh 2026 - Parque Marítimo',
  'Día de Canarias con Bresh, el tardeo más lindo del mundo en una fiesta organizada por Farra World Reserva entradas online',
  37.245468, -6.955979,
  'Parque Marítimo, Parque Marítimo',
  'music',
  '2026-05-30 18:00:00+00',
  '2026-05-30 20:00:00+00',
  team_id, 'upcoming', 'lagenda:42286'
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['music'])
  FROM events WHERE external_id = 'lagenda:42286'
ON CONFLICT DO NOTHING;

-- Fiestas y Romería en Honor a Nuestra Señora de Fátima 2026 [lagenda:41951]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id) VALUES (
  gen_random_uuid(),
  'Fiestas y Romería en Honor a Nuestra Señora de Fátima 2026',
  'En Arona, las Fiestas y Romería en Honor a Nuestra Señora de Fátima 2026 combinan solemnidad religiosa y ambiente festivo. Procesiones, música tradicional y romería campestre honran a la Virgen, con devotos ataviados con trajes típicos, ofrendas y una vibrante muestra de cultura canaria.',
  28.091593, -16.657909,
  'Valle San Lorenzo, Valle San Lorenzo',
  'music',
  '2026-05-30 18:00:00+00',
  '2026-05-30 20:00:00+00',
  team_id, 'upcoming', 'lagenda:41951'
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['music'])
  FROM events WHERE external_id = 'lagenda:41951'
ON CONFLICT DO NOTHING;

-- La Poeteca de Canarias [lagenda:42287]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id) VALUES (
  gen_random_uuid(),
  'La Poeteca de Canarias',
  'La Poeteca de Canarias presenta una nueva agenda de encuentros literarios, recitales y poesía escénica en el Parque Javier Fernández Quesada convirtiendo este espacio en un punto de encuentro para la palabra, la creación y la cultura viva',
  28.485771, -16.315942,
  'La Laguna, La Laguna',
  'music',
  '2026-05-30 18:00:00+00',
  '2026-05-30 20:00:00+00',
  team_id, 'upcoming', 'lagenda:42287'
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['music'])
  FROM events WHERE external_id = 'lagenda:42287'
ON CONFLICT DO NOTHING;

-- Especial Día Canarias Arona 2026 [lagenda:41994]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id) VALUES (
  gen_random_uuid(),
  'Especial Día Canarias Arona 2026',
  'Se realizarán talleres y muestras gastronómicas relacionadas con el producto local o de KM0 durante los meses de abril, mayo y junio en el Mercado del Agricultor de Arona.',
  28.091593, -16.657909,
  'Valle San Lorenzo, Valle San Lorenzo',
  'music',
  '2026-05-30 18:00:00+00',
  '2026-05-30 20:00:00+00',
  team_id, 'upcoming', 'lagenda:41994'
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['music'])
  FROM events WHERE external_id = 'lagenda:41994'
ON CONFLICT DO NOTHING;

-- Feria Agroecológica FICMEC 2026 [lagenda:42069]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id) VALUES (
  gen_random_uuid(),
  'Feria Agroecológica FICMEC 2026',
  'El Festival Internacional de Cine Medioambiental de Canarias (FICMEC) reafirma en 2026 su apuesta por lasoberanía alimentaria y el consumo consciente con la celebración de una nueva edición de su Feriade productos agroecológicos y de sostenibilidad.',
  28.372986, -16.764074,
  'Municipio de Garachico, Municipio de Garachico',
  'music',
  '2026-05-30 18:00:00+00',
  '2026-05-30 20:00:00+00',
  team_id, 'upcoming', 'lagenda:42069'
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['music'])
  FROM events WHERE external_id = 'lagenda:42069'
ON CONFLICT DO NOTHING;

-- Programa 28 FICMEC - Garachico [lagenda:42296]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id) VALUES (
  gen_random_uuid(),
  'Programa 28 FICMEC - Garachico',
  'FICMEC, el Festival de Cine Medioambiental de Canarias divide su vigésima octava edición entre Garachico e Icod de Los Vinos con sus históricas secciones oficiales de cine documental y ficción, animación, y las ya consagradas Vulcanalia, Jugando en Verde o Fotosíntesis, además de una envidiable oferta educativa y cultural Más información, entradas e inscripciones',
  28.326620, -16.751980,
  'Garachico, Garachico',
  'music',
  '2026-05-30 18:00:00+00',
  '2026-05-30 20:00:00+00',
  team_id, 'upcoming', 'lagenda:42296'
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['music'])
  FROM events WHERE external_id = 'lagenda:42296'
ON CONFLICT DO NOTHING;

-- Regenerar Comiendo: Taller + Cocina + Comida [lagenda:42070]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id) VALUES (
  gen_random_uuid(),
  'Regenerar Comiendo: Taller + Cocina + Comida',
  'Un taller sobre alimentación y salud, Taller de cocina con productos locales y de temporada inspirada en la filosofía Slow Food que incluye una comida comunitaria regenerativa compartida alrededor de la mesa',
  28.415902, -16.553296,
  'Puerto de la Cruz, Puerto de la Cruz',
  'music',
  '2026-05-30 18:00:00+00',
  '2026-05-30 20:00:00+00',
  team_id, 'upcoming', 'lagenda:42070'
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['music'])
  FROM events WHERE external_id = 'lagenda:42070'
ON CONFLICT DO NOTHING;

-- ''El Mago que no sale en la tele'' [lagenda:42091]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id) VALUES (
  gen_random_uuid(),
  '''El Mago que no sale en la tele''',
  'Hay magos que salen en la tele… y luego está Malbert. ''El mago que no sale en la tele 2.0'' es la evolución del espectáculo que ha conquistado al público desde la cercanía, el humor y una magia que no necesita filtros ni cámaras para sorprender. Un show renovado, más directo, más afilado y más Malbert que nunca.',
  28.291600, -16.629100,
  'Asociación Cultural Equipo PARA, Asociación Cultural Equipo PARA',
  'music',
  '2026-05-30 18:00:00+00',
  '2026-05-30 20:00:00+00',
  team_id, 'upcoming', 'lagenda:42091'
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['music'])
  FROM events WHERE external_id = 'lagenda:42091'
ON CONFLICT DO NOTHING;

-- Taller de fotografía medioambiental - FICMEC 2026 [lagenda:42092]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id) VALUES (
  gen_random_uuid(),
  'Taller de fotografía medioambiental - FICMEC 2026',
  'Taller de fotografía medioambiental de FICMEC, que este año impartirá Luis Monje, presidente de la Asociación Española de Fotografía Científica y Forense y referente en la materia.',
  28.326620, -16.751980,
  'Garachico, Garachico',
  'music',
  '2026-05-30 18:00:00+00',
  '2026-05-30 20:00:00+00',
  team_id, 'upcoming', 'lagenda:42092'
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['music'])
  FROM events WHERE external_id = 'lagenda:42092'
ON CONFLICT DO NOTHING;

-- Le Cirque Zoppis [lagenda:42103]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id) VALUES (
  gen_random_uuid(),
  'Le Cirque Zoppis',
  'Una experiencia envolvente donde una esfera luminosa, símbolo del sueño de un niño, nos guía a través de un universo mágico lleno de emoción, fantasía y momentos que te dejarán sin palabras.',
  28.487048, -16.314040,
  'Municipio de San Cristóbal de La Laguna, Municipio de San Cristóbal de La Laguna',
  'music',
  '2026-05-30 18:00:00+00',
  '2026-05-30 20:00:00+00',
  team_id, 'upcoming', 'lagenda:42103'
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['music'])
  FROM events WHERE external_id = 'lagenda:42103'
ON CONFLICT DO NOTHING;

-- 69 La Comedia [lagenda:41561]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id) VALUES (
  gen_random_uuid(),
  '69 La Comedia',
  '¿Abrirías tu relación? ¿Lo has pensado? ¿Crees que necesitas clases de sexo? ¿Te has planteado hacer un trío? ¿Te gustaría hacer un intercambio de pareja? ¿Lo has pensado?',
  28.527000, -16.338300,
  'Teatro Unión Tejina, Teatro Unión Tejina',
  'music',
  '2026-05-30 18:00:00+00',
  '2026-05-30 20:00:00+00',
  team_id, 'upcoming', 'lagenda:41561'
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['music'])
  FROM events WHERE external_id = 'lagenda:41561'
ON CONFLICT DO NOTHING;

-- Los Sabandeños - Fin de gira ''60 aniversario'' [lagenda:41661]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id) VALUES (
  gen_random_uuid(),
  'Los Sabandeños - Fin de gira ''60 aniversario''',
  'Han transcurrido ya 60 años desde que un grupo de amigos, del entorno universitario de La Laguna, que tomaron el nombre de Los Sabandeños, decidiera formalizarse como agrupación e iniciara una labor musical ininterrumpida, reflejada en casi un centenar de trabajos discográficos Reserva entradas online',
  28.489700, -16.318123,
  'Teatro Leal, Teatro Leal',
  'music',
  '2026-05-30 18:00:00+00',
  '2026-05-30 20:00:00+00',
  team_id, 'upcoming', 'lagenda:41661'
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['music'])
  FROM events WHERE external_id = 'lagenda:41661'
ON CONFLICT DO NOTHING;

-- XV Ecoislas - FICMEC 2026 [lagenda:42145]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id) VALUES (
  gen_random_uuid(),
  'XV Ecoislas - FICMEC 2026',
  'El Festival Internacional de Cine Medioambiental de Canarias (FICMEC) propone en Garachico un viaje cinematográfico a través de la fragilidad y el futuro de los territorios insulares a través de la visión de cinco filmes reivindicativos rodados en Canarias. ''Roque Largo'', ''Toma Tierra'', ''Pedro Tomás explica el mundo'', ''Kipuka'' y ''A Food Story''',
  40.946454, -4.117123,
  'Antiguo Convento de San Francisco, Antiguo Convento de San Francisco',
  'music',
  '2026-05-30 18:00:00+00',
  '2026-05-30 20:00:00+00',
  team_id, 'upcoming', 'lagenda:42145'
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['music'])
  FROM events WHERE external_id = 'lagenda:42145'
ON CONFLICT DO NOTHING;

-- Fiestas de Mayo 2026 Santa Cruz de Tenerife [lagenda:41682]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id) VALUES (
  gen_random_uuid(),
  'Fiestas de Mayo 2026 Santa Cruz de Tenerife',
  'Santa Cruz de Tenerife ofrece para sus Fiestas de Mayo 2026 un amplio programa con más de un centenar de iniciativas culturales, artísticas, lúdicas y deportivas con motivo de las Fiestas Fundacionales de la capital Programa oficial de las Fiestas de Mayo 2026 en PDF',
  28.469929, -16.254557,
  'Municipio de Santa Cruz, Municipio de Santa Cruz',
  'music',
  '2026-05-30 18:00:00+00',
  '2026-05-30 20:00:00+00',
  team_id, 'upcoming', 'lagenda:41682'
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['music'])
  FROM events WHERE external_id = 'lagenda:41682'
ON CONFLICT DO NOTHING;

-- Día de Canarias en San Miguel de Abona 2026 [lagenda:42219]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id) VALUES (
  gen_random_uuid(),
  'Día de Canarias en San Miguel de Abona 2026',
  'El Ayuntamiento de San Miguel de Abona, a través de la Concejalía de Cultura, conmemora el Día de Canarias con una amplia programación de actividades culturales.',
  28.099205, -16.616791,
  'San Miguel de Abona, San Miguel de Abona',
  'music',
  '2026-05-30 18:00:00+00',
  '2026-05-30 20:00:00+00',
  team_id, 'upcoming', 'lagenda:42219'
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['music'])
  FROM events WHERE external_id = 'lagenda:42219'
ON CONFLICT DO NOTHING;

-- Baile de Taifas de Barrio Nuevo La Laguna 2026 [lagenda:42220]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id) VALUES (
  gen_random_uuid(),
  'Baile de Taifas de Barrio Nuevo La Laguna 2026',
  'Un gran Baile de Magos lleno de tradición, música y buen ambiente. Contaremos con grandes agrupaciones folclóricas y parrandas que pondrán el sabor canario a una jornada muy especial.',
  28.485771, -16.315942,
  'La Laguna, La Laguna',
  'music',
  '2026-05-30 18:00:00+00',
  '2026-05-30 20:00:00+00',
  team_id, 'upcoming', 'lagenda:42220'
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['music'])
  FROM events WHERE external_id = 'lagenda:42220'
ON CONFLICT DO NOTHING;

-- Día de Canarias en San Roque La Laguna 2026 [lagenda:42221]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id) VALUES (
  gen_random_uuid(),
  'Día de Canarias en San Roque La Laguna 2026',
  'Excibición de trillo, bendición de ganado, actividades infantiles y actuaciones musicales en las fiestas del día de Canarias en San Roque.',
  28.485771, -16.315942,
  'La Laguna, La Laguna',
  'music',
  '2026-05-30 18:00:00+00',
  '2026-05-30 20:00:00+00',
  team_id, 'upcoming', 'lagenda:42221'
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['music'])
  FROM events WHERE external_id = 'lagenda:42221'
ON CONFLICT DO NOTHING;

-- Cena Canaria El Calvario 2026 [lagenda:42222]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id) VALUES (
  gen_random_uuid(),
  'Cena Canaria El Calvario 2026',
  'Fiesta Canaria y baile con motivo del Día de Canarias en El Calvario.',
  42.785504, -1.724453,
  'El Calvario, El Calvario',
  'music',
  '2026-05-30 18:00:00+00',
  '2026-05-30 20:00:00+00',
  team_id, 'upcoming', 'lagenda:42222'
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['music'])
  FROM events WHERE external_id = 'lagenda:42222'
ON CONFLICT DO NOTHING;

-- Día de Canarias El Sauzal 2026 [lagenda:42226]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id) VALUES (
  gen_random_uuid(),
  'Día de Canarias El Sauzal 2026',
  'Espectáculo ''Palante y punto'' con Darío López y Yeray Rodríguez y Fiesta Canaria para celebrar el Día de Canarias Reserva en el 617 866 194',
  28.450571, -16.420905,
  'El Sauzal, El Sauzal',
  'music',
  '2026-05-30 18:00:00+00',
  '2026-05-30 20:00:00+00',
  team_id, 'upcoming', 'lagenda:42226'
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['music'])
  FROM events WHERE external_id = 'lagenda:42226'
ON CONFLICT DO NOTHING;

-- ''Pa''lante y punto'' [lagenda:41715]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id) VALUES (
  gen_random_uuid(),
  '''Pa''lante y punto''',
  'Para el 30 de mayo no puede haber nada más canario que Darío López y Yeray Rodríguez. Ambos, humorista y verseador en un espectáculo que une música, improvisación y humor en un mismo escenario',
  28.478868, -16.436560,
  'Teatro El Sauzal, Teatro El Sauzal',
  'music',
  '2026-05-30 18:00:00+00',
  '2026-05-30 20:00:00+00',
  team_id, 'upcoming', 'lagenda:41715'
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['music'])
  FROM events WHERE external_id = 'lagenda:41715'
ON CONFLICT DO NOTHING;

-- Fiestas de Mayo en Los Realejos 2026 [lagenda:41839]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id) VALUES (
  gen_random_uuid(),
  'Fiestas de Mayo en Los Realejos 2026',
  'Llega mayo, el mes en el que Los Realejos se une con más fuerza que nunca, un tiempo en el que la devoción, la tradición y la alegría se entrelazan para dar forma a unas fiestas que nacen del corazón de Los Realejos.',
  28.350311, -16.584952,
  'Los Realejos, Los Realejos',
  'music',
  '2026-05-30 18:00:00+00',
  '2026-05-30 20:00:00+00',
  team_id, 'upcoming', 'lagenda:41839'
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['music'])
  FROM events WHERE external_id = 'lagenda:41839'
ON CONFLICT DO NOTHING;

-- Dia de Canarias 2026 en Tegueste [lagenda:42277]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id) VALUES (
  gen_random_uuid(),
  'Dia de Canarias 2026 en Tegueste',
  'El municipio de Tegueste impulsa actividades para dinamizar la economía local y poner en valor la identidad canaria a través de la cultura, el comercio y su popular mercadillo',
  28.518002, -16.335776,
  'Tegueste, Tegueste',
  'music',
  '2026-05-30 18:00:00+00',
  '2026-05-30 20:00:00+00',
  team_id, 'upcoming', 'lagenda:42277'
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['music'])
  FROM events WHERE external_id = 'lagenda:42277'
ON CONFLICT DO NOTHING;

-- ''Navegarte'' [lagenda:42278]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id) VALUES (
  gen_random_uuid(),
  '''Navegarte''',
  'Ruta teatral que se representarán a bordo del emblemático Correíllo La Palma de la mano de Sergio Miranda y Jaster Luis Reserva entradas online',
  28.467178, -16.250784,
  'Santa Cruz, Santa Cruz',
  'music',
  '2026-05-30 18:00:00+00',
  '2026-05-30 20:00:00+00',
  team_id, 'upcoming', 'lagenda:42278'
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['music'])
  FROM events WHERE external_id = 'lagenda:42278'
ON CONFLICT DO NOTHING;

-- Ruta de las alfombras - La Orotava [lagenda:41932]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id) VALUES (
  gen_random_uuid(),
  'Ruta de las alfombras - La Orotava',
  'José Maza te guía por la Ruta de Las Alfombras en La Orotava durante varias jornadas en esta propuesta dirigida a todos los públicos Inscripciones en cultura@villadelaorotava.org y 922 32 44 44 (Ext. 2565 – 2566)',
  28.389883, -16.523569,
  'La Orotava, La Orotava',
  'music',
  '2026-05-30 18:00:00+00',
  '2026-05-30 20:00:00+00',
  team_id, 'upcoming', 'lagenda:41932'
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['music'])
  FROM events WHERE external_id = 'lagenda:41932'
ON CONFLICT DO NOTHING;

-- En flores - Lecturas y tradiciones [lagenda:41946]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id) VALUES (
  gen_random_uuid(),
  'En flores - Lecturas y tradiciones',
  'El mes de mayo, en La Guancha, viene lleno de propuestas para disfrutar, compartir y poner en valor nuestras tradiciones.',
  28.350862, -16.644864,
  'La Guancha, La Guancha',
  'music',
  '2026-05-30 18:00:00+00',
  '2026-05-30 20:00:00+00',
  team_id, 'upcoming', 'lagenda:41946'
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['music'])
  FROM events WHERE external_id = 'lagenda:41946'
ON CONFLICT DO NOTHING;

-- Día de Canarias 2026 en Los Silos [lagenda:41950]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id) VALUES (
  gen_random_uuid(),
  'Día de Canarias 2026 en Los Silos',
  'El Día de Canarias 2026 en Los Silos reúne aniversario del Mercadillo del Agricultor, una exposición artística, feria de escritores y cantautores, Paseo Romero con centros educativos, Baile de Magos Infantil y un fin de semana festivo con concierto y Gran Baile de Magos, reforzando tradición y comunidad.',
  28.352347, -16.814252,
  'Los Silos, Los Silos',
  'music',
  '2026-05-30 18:00:00+00',
  '2026-05-30 20:00:00+00',
  team_id, 'upcoming', 'lagenda:41950'
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['music'])
  FROM events WHERE external_id = 'lagenda:41950'
ON CONFLICT DO NOTHING;

-- III Baile de magos infantil - La Orotava 2026 [lagenda:42337]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id) VALUES (
  gen_random_uuid(),
  'III Baile de magos infantil - La Orotava 2026',
  'Tras las celebraciones del Día de Canarias, en La Orotava los niños no se quitan el traje de mago y celebran la tercera edición de su baile infantil',
  28.791618, -17.776700,
  'Orotava, Orotava',
  'music',
  '2026-05-31 18:00:00+00',
  '2026-05-31 20:00:00+00',
  team_id, 'upcoming', 'lagenda:42337'
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['music'])
  FROM events WHERE external_id = 'lagenda:42337'
ON CONFLICT DO NOTHING;

-- ''Gospel Shine Voices'' [lagenda:41966]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id) VALUES (
  gen_random_uuid(),
  '''Gospel Shine Voices''',
  'Concierto de Gospel Shine Voices bajo la dirección de Gustavo Campos. Una velada emocionante en la que la fuerza de las voces y la espiritualidad del góspel llenarán de energía y emoción este espacio único en la Punta del Hidalgo',
  28.569197, -16.321739,
  'Punta del Hidalgo, Punta del Hidalgo',
  'music',
  '2026-05-31 18:00:00+00',
  '2026-05-31 20:00:00+00',
  team_id, 'upcoming', 'lagenda:41966'
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['music'])
  FROM events WHERE external_id = 'lagenda:41966'
ON CONFLICT DO NOTHING;

-- ''Sentidos''. Diego Expósito y Fanny Rodrigez [lagenda:42009]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id) VALUES (
  gen_random_uuid(),
  '''Sentidos''. Diego Expósito y Fanny Rodrigez',
  'Concierto de soul, jazz y pop, a piano y voz, interpretado por Diego Expósito y Fanny Rodríguez',
  36.717993, -4.488701,
  'Paraninfo, Paraninfo',
  'music',
  '2026-05-31 18:00:00+00',
  '2026-05-31 20:00:00+00',
  team_id, 'upcoming', 'lagenda:42009'
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['music'])
  FROM events WHERE external_id = 'lagenda:42009'
ON CONFLICT DO NOTHING;

-- ''Vaiana, el musical'' [lagenda:41660]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id) VALUES (
  gen_random_uuid(),
  '''Vaiana, el musical''',
  'La entusiasta Vaiana está destinada a convertirse algún día en la jefa de la isla de Motonui. Cuando los aldeanos no pueden pescar ningún pez y todas las cosechas fallan, Vaiana descubre que el semidiós Maui causó el infortunio después de robar el corazón de la diosa Te Fiti Reserva entradas online',
  28.489700, -16.318123,
  'Teatro Leal, Teatro Leal',
  'music',
  '2026-05-31 18:00:00+00',
  '2026-05-31 20:00:00+00',
  team_id, 'upcoming', 'lagenda:41660'
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['music'])
  FROM events WHERE external_id = 'lagenda:41660'
ON CONFLICT DO NOTHING;

-- Taller ''La lengua en la tierra'' 2026 [lagenda:42240]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id) VALUES (
  gen_random_uuid(),
  'Taller ''La lengua en la tierra'' 2026',
  'En este taller, la poeta Luz Pichel nos propone acercarnos a la escritura como un espacio de encuentro, escucha y sedimentación de la vida. Un obradoiro entendido no solo como taller, sino como lugar donde hacer -como quien hace pan- : pensar juntas, escribir, compartir y generar herramientas para tejer y destejer.',
  28.291600, -16.629100,
  'TEA Tenerife Espacio de las Artes, TEA Tenerife Espacio de las Artes',
  'music',
  '2026-05-31 18:00:00+00',
  '2026-05-31 20:00:00+00',
  team_id, 'upcoming', 'lagenda:42240'
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['music'])
  FROM events WHERE external_id = 'lagenda:42240'
ON CONFLICT DO NOTHING;

-- Brunch de cine en FICMEC [lagenda:42250]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id) VALUES (
  gen_random_uuid(),
  'Brunch de cine en FICMEC',
  'El restaurante El Rebojo diseñará un menú inspirado en el documental ''Aisha’s Story'', que tendrá su estreno en FICMEC Reserva entradas online',
  40.946454, -4.117123,
  'Antiguo Convento de San Francisco, Antiguo Convento de San Francisco',
  'music',
  '2026-05-31 18:00:00+00',
  '2026-05-31 20:00:00+00',
  team_id, 'upcoming', 'lagenda:42250'
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['music'])
  FROM events WHERE external_id = 'lagenda:42250'
ON CONFLICT DO NOTHING;

-- ''Cuentos Sin Principios, Desnudos y Algún Desenlace'' [lagenda:41411]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id) VALUES (
  gen_random_uuid(),
  '''Cuentos Sin Principios, Desnudos y Algún Desenlace''',
  'Sesión de Cuentacuentos para público adulto ''Cuentos Sin Principios, Desnudos y Algún Desenlace'' realizada por Silvia Torrents y adaptada a lengua de signos.',
  28.291600, -16.629100,
  'Convento Franciscano San Luis Obispo, Convento Franciscano San Luis Obispo',
  'music',
  '2026-06-01 18:00:00+00',
  '2026-06-01 20:00:00+00',
  team_id, 'upcoming', 'lagenda:41411'
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['music'])
  FROM events WHERE external_id = 'lagenda:41411'
ON CONFLICT DO NOTHING;

-- Suma Festival 2026 [lagenda:42288]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id) VALUES (
  gen_random_uuid(),
  'Suma Festival 2026',
  'VII Edición de Suma Festival, Santa Úrsula Música y Arte, con una variada selección de artistas, talleres y actuaciones en vivo. Álvaro Gacía, Abubukaka, Pieles, Anaé, Darío López.',
  28.425142, -16.491538,
  'Municipio de Santa Úrsula, Municipio de Santa Úrsula',
  'music',
  '2026-06-02 18:00:00+00',
  '2026-06-02 20:00:00+00',
  team_id, 'upcoming', 'lagenda:42288'
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['music'])
  FROM events WHERE external_id = 'lagenda:42288'
ON CONFLICT DO NOTHING;

-- Dúo del Valle [lagenda:41697]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id) VALUES (
  gen_random_uuid(),
  'Dúo del Valle',
  'Recital del Dúo del Valle, a cargo de los hermanos Víctor y Luis del Valle, quienes interpretarán a dos pianos el programa ''El jardín de lo imposible'' dentro de los conciertos de piano del Ciclo de Cámara de Auditorio de Tenerife Reserva entradas online',
  28.456074, -16.251243,
  'Auditorio de Tenerife Adán Martín, Auditorio de Tenerife Adán Martín',
  'music',
  '2026-06-02 18:00:00+00',
  '2026-06-02 20:00:00+00',
  team_id, 'upcoming', 'lagenda:41697'
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['music'])
  FROM events WHERE external_id = 'lagenda:41697'
ON CONFLICT DO NOTHING;

-- Taller ''La magia de las letras'' [lagenda:41998]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id) VALUES (
  gen_random_uuid(),
  'Taller ''La magia de las letras''',
  '''La magia de las letras'' es un taller impartido por el escritor Víctor Conde centrado en la narrativa clásica. El alumnado deberá redactar sus propios textos y posteriormente, se realizará una puesta en común con lecturas y correcciones. Las personas interesadas en asistir a este taller deben inscribirse previamente enviando un correo electrónico a info@libreriadelcabildo.net hasta completar el aforo.',
  28.104881, -15.416649,
  'Librería del Cabildo, Librería del Cabildo',
  'music',
  '2026-06-03 18:00:00+00',
  '2026-06-03 20:00:00+00',
  team_id, 'upcoming', 'lagenda:41998'
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['music'])
  FROM events WHERE external_id = 'lagenda:41998'
ON CONFLICT DO NOTHING;

-- ''Tres noches en Ítaca'' - Primavera en la Fundación 2026 [lagenda:40529]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id) VALUES (
  gen_random_uuid(),
  '''Tres noches en Ítaca'' - Primavera en la Fundación 2026',
  'Tragicomedia de Alberto Conejero interpretada por Marta Nieto, Cecilia Freire y Amaia Lizarralde, ambientada en una casa frente al mar en Ítaca donde tres hermanas afrontan el duelo por su madre y revisitan su pasado desde la memoria, la luz y la imaginación. La obra, profundiza en las relaciones entre las hermanas Ariadna, Penélope y Elena, en el legado de una madre excéntrica y en las preguntas sobre cómo renacer, reescribir la propia vida y mantener vivas las Humanidades en tiempos inciertos. Reserva entradas online',
  28.463600, -16.251800,
  'Espacio Cultural CajaCanarias Santa Cruz, Espacio Cultural CajaCanarias Santa Cruz',
  'music',
  '2026-06-03 18:00:00+00',
  '2026-06-03 20:00:00+00',
  team_id, 'upcoming', 'lagenda:40529'
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['music'])
  FROM events WHERE external_id = 'lagenda:40529'
ON CONFLICT DO NOTHING;

-- Rutas ''La Letra Esmeralda'' [lagenda:42118]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id) VALUES (
  gen_random_uuid(),
  'Rutas ''La Letra Esmeralda''',
  'El Centro de Documentación de Canarias y América organiza las rutas gratuitas ''La Letra Esmeralda'', en Santa Cruz de Tenerife y La Laguna. Los participantes vivirán una experiencia única visitando lugares emblemáticos relacionados con la vida de Esmeralda Cervantes',
  37.372751, -5.947118,
  'C.C. Meridiano, C.C. Meridiano',
  'music',
  '2026-06-03 18:00:00+00',
  '2026-06-03 20:00:00+00',
  team_id, 'upcoming', 'lagenda:42118'
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['music'])
  FROM events WHERE external_id = 'lagenda:42118'
ON CONFLICT DO NOTHING;

-- Swing Hits [lagenda:42173]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id) VALUES (
  gen_random_uuid(),
  'Swing Hits',
  'Un recorrido por el repertorio de swing y de soul en formato Big Band',
  28.527000, -16.338300,
  'Teatro Unión Tejina, Teatro Unión Tejina',
  'music',
  '2026-06-03 18:00:00+00',
  '2026-06-03 20:00:00+00',
  team_id, 'upcoming', 'lagenda:42173'
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['music'])
  FROM events WHERE external_id = 'lagenda:42173'
ON CONFLICT DO NOTHING;

-- Just Lío [lagenda:42408]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id) VALUES (
  gen_random_uuid(),
  'Just Lío',
  'La nueva experiencia de tardeo de Palapa Beach Club. Cócteles frente al mar, DJs en directo, buena música y el mejor ambiente para alargar la tarde hasta la puesta de sol. Un plan pensado para disfrutar, desconectar y dejarse llevar. Porque a veces una copa lleva a otra, y la tarde acaba liándose.',
  28.060197, -16.731053,
  'Playa de Las Américas, Playa de Las Américas',
  'music',
  '2026-06-04 18:00:00+00',
  '2026-06-04 20:00:00+00',
  team_id, 'upcoming', 'lagenda:42408'
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['music'])
  FROM events WHERE external_id = 'lagenda:42408'
ON CONFLICT DO NOTHING;

-- Programa 28 FICMEC - Icod de los Vinos [lagenda:42297]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id) VALUES (
  gen_random_uuid(),
  'Programa 28 FICMEC - Icod de los Vinos',
  'FICMEC, el Festival de Cine Medioambiental de Canarias divide su vigésima octava edición entre Garachico e Icod de Los Vinos con sus históricas secciones oficiales de cine documental y ficción, animación, y las ya consagradas Vulcanalia, Jugando en Verde o Fotosíntesis, además de una envidiable oferta educativa y cultural Más información, entradas e inscripciones',
  28.366453, -16.721122,
  'Icod, Icod',
  'music',
  '2026-06-04 18:00:00+00',
  '2026-06-04 20:00:00+00',
  team_id, 'upcoming', 'lagenda:42297'
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['music'])
  FROM events WHERE external_id = 'lagenda:42297'
ON CONFLICT DO NOTHING;

-- ''Cada loco con su tema'' [lagenda:42100]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id) VALUES (
  gen_random_uuid(),
  '''Cada loco con su tema''',
  'Una comedia fresca, ágil y para todos los públicos que busca provocar carcajadas inmediatas con personajes entrañables y delirantes Reserva entradas online',
  28.291600, -16.629100,
  'L''Incanto, L''Incanto',
  'music',
  '2026-06-04 18:00:00+00',
  '2026-06-04 20:00:00+00',
  team_id, 'upcoming', 'lagenda:42100'
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['music'])
  FROM events WHERE external_id = 'lagenda:42100'
ON CONFLICT DO NOTHING;

-- Semana Internacional de la Moda de Tenerife 2026 [lagenda:42237]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id) VALUES (
  gen_random_uuid(),
  'Semana Internacional de la Moda de Tenerife 2026',
  'La Semana Internacional de la Moda de Tenerife regresa en 2026 con una apuesta dedicada por las tendencias urbanas',
  28.454605, -16.257730,
  'Recinto Ferial, Recinto Ferial',
  'music',
  '2026-06-04 18:00:00+00',
  '2026-06-04 20:00:00+00',
  team_id, 'upcoming', 'lagenda:42237'
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['music'])
  FROM events WHERE external_id = 'lagenda:42237'
ON CONFLICT DO NOTHING;

-- Ballet Stars Gala [lagenda:41716]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id) VALUES (
  gen_random_uuid(),
  'Ballet Stars Gala',
  'En esta noche mágica, se podrá disfrutar de los más impresionantes solos de algunos de los ballets más queridos de todos los tiempos; ''El Lago de los Cisnes'', ''Don Quijote'', ''Raymonda'' o ''El Corsario'', entre otros. Una oportunidad única de disfrutar del ballet clásico en su máxima expresión.',
  28.478868, -16.436560,
  'Teatro El Sauzal, Teatro El Sauzal',
  'music',
  '2026-06-04 18:00:00+00',
  '2026-06-04 20:00:00+00',
  team_id, 'upcoming', 'lagenda:41716'
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['music'])
  FROM events WHERE external_id = 'lagenda:41716'
ON CONFLICT DO NOTHING;

-- ''El amigo silencioso'' [lagenda:42391]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id) VALUES (
  gen_random_uuid(),
  '''El amigo silencioso''',
  'Tres historias ambientadas en épocas distintas que se suceden a los pies de un un ginkgo centenario. Este árbol, testigo silencioso, ha observado durante más de un siglo los tranquilos ritmos de la transformación a lo largo de tres vidas humanas. ''El amigo silencioso'' de Ildikó Enyedi fué Ganadora del Premio del Jurado de la Crítica Internacional en el Festival de Cine de Venecia y de la Espiga de Plata en la Seminci Reserva entradas online',
  28.291600, -16.629100,
  'TEA Tenerife Espacio de las Artes, TEA Tenerife Espacio de las Artes',
  'music',
  '2026-06-05 18:00:00+00',
  '2026-06-05 20:00:00+00',
  team_id, 'upcoming', 'lagenda:42391'
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['music'])
  FROM events WHERE external_id = 'lagenda:42391'
ON CONFLICT DO NOTHING;

-- Alex Janssen Trío [lagenda:42326]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id) VALUES (
  gen_random_uuid(),
  'Alex Janssen Trío',
  'Concierto de jazz en el que disfrutaremos de envolventes melodías y pasajes improvisados a través de texturas, ritmos y armonías, que reflejan las influencias individuales de cada componente',
  28.291600, -16.629100,
  'Café Teatro Rayuela, Café Teatro Rayuela',
  'music',
  '2026-06-05 18:00:00+00',
  '2026-06-05 20:00:00+00',
  team_id, 'upcoming', 'lagenda:42326'
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['music'])
  FROM events WHERE external_id = 'lagenda:42326'
ON CONFLICT DO NOTHING;

-- Baile de Magos La Orotava 2026 [lagenda:42338]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id) VALUES (
  gen_random_uuid(),
  'Baile de Magos La Orotava 2026',
  'Jornada llena de actividad en las Fiestas de La Orotava 2026 con grandes bailes, tradición, orquesta y gastronomía popular',
  28.389883, -16.523569,
  'La Orotava, La Orotava',
  'music',
  '2026-06-05 18:00:00+00',
  '2026-06-05 20:00:00+00',
  team_id, 'upcoming', 'lagenda:42338'
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['music'])
  FROM events WHERE external_id = 'lagenda:42338'
ON CONFLICT DO NOTHING;

-- ''La voracidad. Entre vampiros y zombies'' [lagenda:42366]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id) VALUES (
  gen_random_uuid(),
  '''La voracidad. Entre vampiros y zombies''',
  'Aranza Coello realiza una residencia de investigación dramatúrgica en La Salita ''La voracidad (entre vampiros y zombies)''. Un encuentro donde jugar a compartir experiencias y visiones sobre el sector turístico. No es una charla, no es una clase, es un espacio donde exponer, de otra manera, nuestra mirada sobre el uso del territorio.',
  28.456074, -16.251243,
  'Auditorio de Tenerife Adán Martín, Auditorio de Tenerife Adán Martín',
  'music',
  '2026-06-05 18:00:00+00',
  '2026-06-05 20:00:00+00',
  team_id, 'upcoming', 'lagenda:42366'
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['music'])
  FROM events WHERE external_id = 'lagenda:42366'
ON CONFLICT DO NOTHING;

-- The Molotovs [lagenda:42294]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id) VALUES (
  gen_random_uuid(),
  'The Molotovs',
  'El dúo británico de los hermanos Matt e Issey Cartlidge se acerca a Tenerife dentro de una envidiable gira que les lleva por todo el planeta Reserva entradas online',
  28.291600, -16.629100,
  'Aguere Espacio Cultural, Aguere Espacio Cultural',
  'music',
  '2026-06-05 18:00:00+00',
  '2026-06-05 20:00:00+00',
  team_id, 'upcoming', 'lagenda:42294'
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['music'])
  FROM events WHERE external_id = 'lagenda:42294'
ON CONFLICT DO NOTHING;

-- ''Yo,tu,ella'' [lagenda:42101]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id) VALUES (
  gen_random_uuid(),
  '''Yo,tu,ella''',
  'Una comedia confesional escrita por Mónica Montañés y dirigida por Crisol Carabal. Tres mujeres emprenden un inesperado viaje emocional entre confesiones, risas y reconciliación personal. Reserva entradas online',
  28.291600, -16.629100,
  'L''Incanto, L''Incanto',
  'music',
  '2026-06-05 18:00:00+00',
  '2026-06-05 20:00:00+00',
  team_id, 'upcoming', 'lagenda:42101'
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['music'])
  FROM events WHERE external_id = 'lagenda:42101'
ON CONFLICT DO NOTHING;

-- La Bien Querida - Primavera en la Fundación 2026 [lagenda:40531]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id) VALUES (
  gen_random_uuid(),
  'La Bien Querida - Primavera en la Fundación 2026',
  'La Bien Querida es el proyecto de Ana Fernández-Villaverde, figura clave del pop alternativo español, cuyas canciones mezclan electrónica y pop con letras románticas y existenciales; desde ''Romancero'' hasta trabajos como ''Fiesta'', ''Ceremonia'', ''Fuego'' o ''Paprika'', la artista ha construido un universo sonoro muy personal Reserva entradas online',
  28.463600, -16.251800,
  'Espacio Cultural CajaCanarias Santa Cruz, Espacio Cultural CajaCanarias Santa Cruz',
  'music',
  '2026-06-05 18:00:00+00',
  '2026-06-05 20:00:00+00',
  team_id, 'upcoming', 'lagenda:40531'
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['music'])
  FROM events WHERE external_id = 'lagenda:40531'
ON CONFLICT DO NOTHING;

-- Luis Piedrahita [lagenda:41662]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id) VALUES (
  gen_random_uuid(),
  'Luis Piedrahita',
  '''Apocalípticamente correcto'' es el nuevo show de Luis Piedrahita, un ingenioso monólogo sobre la libertad y el destino. Son temas delicados, pero Luis no teme a nada. El miedo espanta la risa y, de modo recíproco, la risa espanta al miedo. Reserva entradas online',
  28.489700, -16.318123,
  'Teatro Leal, Teatro Leal',
  'music',
  '2026-06-05 18:00:00+00',
  '2026-06-05 20:00:00+00',
  team_id, 'upcoming', 'lagenda:41662'
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['music'])
  FROM events WHERE external_id = 'lagenda:41662'
ON CONFLICT DO NOTHING;

-- Paredes - Marichal - Glez Torres [lagenda:42164]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id) VALUES (
  gen_random_uuid(),
  'Paredes - Marichal - Glez Torres',
  'Tres trayectorias, tres lenguajes, un único momento irrepetible. David Paredes , Ricardo Marichal y Fran Glez Torres se encuentran por primera vez sobre el escenario para explorar sin mapa: improvisación pura, cruce de escenas y diálogo en tiempo real. reserva entradas online',
  28.291600, -16.629100,
  'Asociación Cultural Equipo PARA, Asociación Cultural Equipo PARA',
  'music',
  '2026-06-05 18:00:00+00',
  '2026-06-05 20:00:00+00',
  team_id, 'upcoming', 'lagenda:42164'
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['music'])
  FROM events WHERE external_id = 'lagenda:42164'
ON CONFLICT DO NOTHING;

-- Variaciones sobre Temas canarios - FMUC 2026 [lagenda:41694]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id) VALUES (
  gen_random_uuid(),
  'Variaciones sobre Temas canarios - FMUC 2026',
  'El Festival de Música Contemporánea de Tenerife (FMUC), edición 2026, programa Variaciones sobre Temas canarios, una obra de estreno de Francis Hernández, pianista, compositor y director musical, considerado un músico ecléctico que ha alternado la música académica con la música popular. Este año, estrenará una nueva obra compuesta para esta edición del festival. Reserva entradas online',
  28.456074, -16.251243,
  'Auditorio de Tenerife Adán Martín, Auditorio de Tenerife Adán Martín',
  'music',
  '2026-06-05 18:00:00+00',
  '2026-06-05 20:00:00+00',
  team_id, 'upcoming', 'lagenda:41694'
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['music'])
  FROM events WHERE external_id = 'lagenda:41694'
ON CONFLICT DO NOTHING;

-- Ballet Stars Gala [lagenda:41730]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id) VALUES (
  gen_random_uuid(),
  'Ballet Stars Gala',
  'En esta noche mágica, se podrá disfrutar de los más impresionantes solos de algunos de los ballets más queridos de todos los tiempos; ''El Lago de los Cisnes'', ''Don Quijote'', ''Raymonda'' o ''El Corsario'', entre otros. Una oportunidad única de disfrutar del ballet clásico en su máxima expresión.',
  28.291600, -16.629100,
  'Auditorio Infanta Leonor, Auditorio Infanta Leonor',
  'music',
  '2026-06-05 18:00:00+00',
  '2026-06-05 20:00:00+00',
  team_id, 'upcoming', 'lagenda:41730'
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['music'])
  FROM events WHERE external_id = 'lagenda:41730'
ON CONFLICT DO NOTHING;

-- ''Tras la estela de Shackleton'' [lagenda:42272]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id) VALUES (
  gen_random_uuid(),
  '''Tras la estela de Shackleton''',
  'Proyección del documental ''Tras la estela de Shackleton'' donde el alpinista y divulgador Juan Diego Amador nos cuenta su viaje a la Ántartida, siguiendo los pasos del célebre aventurero Sir Ernest Shackleton. Una dramática e histórica experiencia de supervivencia que las personas asistentes podrán compartir y desgranar junto al en un coloquio posterior. Más información y entradas',
  28.467178, -16.250784,
  'Santa Cruz, Santa Cruz',
  'music',
  '2026-06-05 18:00:00+00',
  '2026-06-05 20:00:00+00',
  team_id, 'upcoming', 'lagenda:42272'
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['music'])
  FROM events WHERE external_id = 'lagenda:42272'
ON CONFLICT DO NOTHING;

-- ''Hortus Hesperidum'' [lagenda:42406]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id) VALUES (
  gen_random_uuid(),
  '''Hortus Hesperidum''',
  '''Hortus Hesperidum'' es un proyecto personal en torno al mito del Jardín de las Hespéride a cargo de Manolo Yanes que cuenta con la colaboración de 19 artistas de las Islas Canarias. Estas aportaciones provienen además de otras disciplinas artísticas como literatura, escultura, literatura, música y vídeoarte.',
  28.291600, -16.629100,
  'Museo de la Naturaleza y Arqueología, Museo de la Naturaleza y Arqueología',
  'music',
  '2026-06-06 18:00:00+00',
  '2026-06-06 20:00:00+00',
  team_id, 'upcoming', 'lagenda:42406'
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['music'])
  FROM events WHERE external_id = 'lagenda:42406'
ON CONFLICT DO NOTHING;

-- Fiestas del Corpus Christi La Orotava 2026 [lagenda:42339]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id) VALUES (
  gen_random_uuid(),
  'Fiestas del Corpus Christi La Orotava 2026',
  'Las celebraciones incluyen confección de alfombras, eucaristías y procesiones del Corpus en varias parroquias, junto a concursos de arrastre, rutas históricas y exposiciones. Se suman recitales, conciertos, elección de la Romera Mayor y actividades en el Liceo de Taoro, además de la Fiesta de los Vinos y el Festival Parrandero.',
  28.389883, -16.523569,
  'La Orotava, La Orotava',
  'music',
  '2026-06-06 18:00:00+00',
  '2026-06-06 20:00:00+00',
  team_id, 'upcoming', 'lagenda:42339'
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['music'])
  FROM events WHERE external_id = 'lagenda:42339'
ON CONFLICT DO NOTHING;

-- Fimucité20 [lagenda:42344]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id) VALUES (
  gen_random_uuid(),
  'Fimucité20',
  'Vigésimo aniversario de Fimucité que incluirá grandes conciertos y una programación dedicada a la música de cine de todos los tiempos con invitados de excepción y homenajes Más información y entradas',
  28.293578, -16.621447,
  'Tenerife, Tenerife',
  'music',
  '2026-06-06 18:00:00+00',
  '2026-06-06 20:00:00+00',
  team_id, 'upcoming', 'lagenda:42344'
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['music'])
  FROM events WHERE external_id = 'lagenda:42344'
ON CONFLICT DO NOTHING;

-- Aarón Gómez & Guacimara Gil [lagenda:42350]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id) VALUES (
  gen_random_uuid(),
  'Aarón Gómez & Guacimara Gil',
  'Dos amigos, dos locos del humor, se suben al escenario para compartir risas como solo ellos saben hacer. Aarón Gómez, con una carrera consolidada como uno de los cómicos más queridos de Canarias, y Guacimara Gil, actriz e improvisadora sin límites, se unen para ofrecer una noche inolvidable Reserva entradas online',
  28.485771, -16.315942,
  'La Laguna, La Laguna',
  'music',
  '2026-06-06 18:00:00+00',
  '2026-06-06 20:00:00+00',
  team_id, 'upcoming', 'lagenda:42350'
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['music'])
  FROM events WHERE external_id = 'lagenda:42350'
ON CONFLICT DO NOTHING;

-- Las Arañas del Neptuno [lagenda:42368]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id) VALUES (
  gen_random_uuid(),
  'Las Arañas del Neptuno',
  'Junio llega con mucho oleaje a Santa Cruz de Tenerife, tanto que las olas llegarán hasta el escenario del Lone Star. Los chicos de Las Arañas del Neptuno se encargarán de hacer memorable una noche de buen surf rock en la que además contarán con una DJ session de vinilos a cargo de David Makingtime como complemento perfecto de la velada que huele a salitre y a amplificadores de válvulas.',
  28.470601, -16.247554,
  'Lone Star, Lone Star',
  'music',
  '2026-06-06 18:00:00+00',
  '2026-06-06 20:00:00+00',
  team_id, 'upcoming', 'lagenda:42368'
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['music'])
  FROM events WHERE external_id = 'lagenda:42368'
ON CONFLICT DO NOTHING;

-- Alfombra Joven - Corpus Christi 2026 [lagenda:41954]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id) VALUES (
  gen_random_uuid(),
  'Alfombra Joven - Corpus Christi 2026',
  'Los y las jóvenes del municipio podrán participar en la elaboración de la alfombra joven con motivo del Corpus Christi, una tradición muy arraigada en nuestra localidad.',
  28.139440, -16.739456,
  'Adeje, Adeje',
  'music',
  '2026-06-06 18:00:00+00',
  '2026-06-06 20:00:00+00',
  team_id, 'upcoming', 'lagenda:41954'
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['music'])
  FROM events WHERE external_id = 'lagenda:41954'
ON CONFLICT DO NOTHING;

-- Saoko 2026 [lagenda:42039]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id) VALUES (
  gen_random_uuid(),
  'Saoko 2026',
  'La programación musical incluirá los directos de Abhir y Lewis Potter, junto con las sesiones de los DJs Bumbum, Laureano y Kiddo. Saoko music festival refuerza su apuesta por una experiencia global que integra escenografía temática, espacios visuales y diferentes elementos sorpresa. Las entradas y toda la información del evento están disponibles a través de las redes socialesoficiales de @saokotenerife.',
  28.448286, -16.295212,
  'El Polvorín - Taco, El Polvorín - Taco',
  'music',
  '2026-06-06 18:00:00+00',
  '2026-06-06 20:00:00+00',
  team_id, 'upcoming', 'lagenda:42039'
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['music'])
  FROM events WHERE external_id = 'lagenda:42039'
ON CONFLICT DO NOTHING;

-- Julia Rodríguez [lagenda:42305]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id) VALUES (
  gen_random_uuid(),
  'Julia Rodríguez',
  'Concierto de Julia Rodríguez enmarcado en el programa ‘Cultura y raíces’ del Gobierno de Canarias.  Su primer EP ‘Hacia la vida’, fue seleccionado como mejor disco de músicas de raíz en los Premios Canarios de la Música en 2025. Con este ha recorrido las 8 islas, compartiendo su inconfundible sensibilidad y fuerza. Reserva entradas online',
  41.128143, 1.206468,
  'Espacio La Granja, Espacio La Granja',
  'music',
  '2026-06-06 18:00:00+00',
  '2026-06-06 20:00:00+00',
  team_id, 'upcoming', 'lagenda:42305'
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['music'])
  FROM events WHERE external_id = 'lagenda:42305'
ON CONFLICT DO NOTHING;

-- ''Minor Inter Partes'' [lagenda:42323]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id) VALUES (
  gen_random_uuid(),
  '''Minor Inter Partes''',
  '''Minor inter partes'' es la segunda parte de la trilogía que se inició con ''Baleiro'' y, en cierto modo, sucede después. Vaciados los símbolos y sus significados, vaciados los discursos y los relatos el público acompañará a Ensalle y Juan Navarro a la “trastienda” de aquel plató cutre de televisión, al backstage de aquel “reality fake”. Reserva entradas online',
  39.958949, -4.832246,
  'Teatro Victoria, Teatro Victoria',
  'music',
  '2026-06-06 18:00:00+00',
  '2026-06-06 20:00:00+00',
  team_id, 'upcoming', 'lagenda:42323'
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['music'])
  FROM events WHERE external_id = 'lagenda:42323'
ON CONFLICT DO NOTHING;

-- UPRISING - Muse Tributo [lagenda:41602]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id) VALUES (
  gen_random_uuid(),
  'UPRISING - Muse Tributo',
  'UPRISING realizaran un extenso repaso a los temas más representativos de la discografía de los británicos, con un espectáculo audiovisual que ya acumula excelentes críticas en las diversas giras nacionales que los albaceteños han llevado a cabo.',
  28.291600, -16.629100,
  'Aguere Espacio Cultural, Aguere Espacio Cultural',
  'music',
  '2026-06-06 18:00:00+00',
  '2026-06-06 20:00:00+00',
  team_id, 'upcoming', 'lagenda:41602'
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['music'])
  FROM events WHERE external_id = 'lagenda:41602'
ON CONFLICT DO NOTHING;

-- Fotosíntesis - FICMEC 2026 [lagenda:42138]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id) VALUES (
  gen_random_uuid(),
  'Fotosíntesis - FICMEC 2026',
  'Fotosíntesis refuerza así su papel dentro de FICMEC como un espacio de reflexión y aprendizaje en torno a una agricultura más resiliente, consciente y comprometida con el futuro del territorio.',
  28.366453, -16.721122,
  'Icod, Icod',
  'music',
  '2026-06-06 18:00:00+00',
  '2026-06-06 20:00:00+00',
  team_id, 'upcoming', 'lagenda:42138'
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['music'])
  FROM events WHERE external_id = 'lagenda:42138'
ON CONFLICT DO NOTHING;

-- ''La cajita de latón'' [lagenda:42150]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id) VALUES (
  gen_random_uuid(),
  '''La cajita de latón''',
  'María Rosa Alonso, se prepara para partir de Canarias a Venezuela, después de sufrir una dura injusticia en su puesto de trabajo en la universidad. preocupados por ella la visitan en un intento fallido por hacer que se quede en la isla. Una pieza que recoge la importancia que posee la amistad en la vida y cómo puede permanecer a través del tiempo y la distancia. Reserva previa en el WhatsApp +34 685 656 053',
  28.291600, -16.629100,
  'Zálatta Espacio Escénico, Zálatta Espacio Escénico',
  'music',
  '2026-06-06 18:00:00+00',
  '2026-06-06 20:00:00+00',
  team_id, 'upcoming', 'lagenda:42150'
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['music'])
  FROM events WHERE external_id = 'lagenda:42150'
ON CONFLICT DO NOTHING;

-- Alex Janssen Quartet [lagenda:42165]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id) VALUES (
  gen_random_uuid(),
  'Alex Janssen Quartet',
  'Alex Janssen, guitarrista de Jazz uruguayo afincado en Canarias desde 1993, desarrolla una intensa actividad musical, participando en una infinidad de proyectos que lo llevan a tocar tanto en las Islas como en el continente. reserva entradas online',
  28.291600, -16.629100,
  'Asociación Cultural Equipo PARA, Asociación Cultural Equipo PARA',
  'music',
  '2026-06-06 18:00:00+00',
  '2026-06-06 20:00:00+00',
  team_id, 'upcoming', 'lagenda:42165'
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['music'])
  FROM events WHERE external_id = 'lagenda:42165'
ON CONFLICT DO NOTHING;

-- Marta Klimasara - FMUC 2026 [lagenda:41695]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id) VALUES (
  gen_random_uuid(),
  'Marta Klimasara - FMUC 2026',
  'El Festival de Música Contemporánea de Tenerife (FMUC), edición 2026, programa un concierto a cargo de la prestigiosa percusionista Marta Klimasara, acompañada por  Andrea Domínguez, María Vera y Verónica Cagigao Reserva entradas online',
  28.456074, -16.251243,
  'Auditorio de Tenerife Adán Martín, Auditorio de Tenerife Adán Martín',
  'music',
  '2026-06-06 18:00:00+00',
  '2026-06-06 20:00:00+00',
  team_id, 'upcoming', 'lagenda:41695'
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['music'])
  FROM events WHERE external_id = 'lagenda:41695'
ON CONFLICT DO NOTHING;

-- Rod & Tina [lagenda:41731]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id) VALUES (
  gen_random_uuid(),
  'Rod & Tina',
  'Rod and the Facez y Tina Forever. Dos espléndidos tributos a Rod Stewart y Tina Turner con los grandes éxitos de estas inolvidables leyendas de la música universal',
  28.291600, -16.629100,
  'Auditorio Infanta Leonor, Auditorio Infanta Leonor',
  'music',
  '2026-06-06 18:00:00+00',
  '2026-06-06 20:00:00+00',
  team_id, 'upcoming', 'lagenda:41731'
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['music'])
  FROM events WHERE external_id = 'lagenda:41731'
ON CONFLICT DO NOTHING;

-- Cajón Desastre - Adri & Rod [lagenda:41757]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id) VALUES (
  gen_random_uuid(),
  'Cajón Desastre - Adri & Rod',
  'Un show divertido, afilado y único. Anécdotas del público que se convierten en historias improvisadas, escenas envueltas por la música en vivo del DJ improvisador MVBA, y ese equilibrio brillante entre el humor, la empatía y la locura más canalla.',
  28.291600, -16.629100,
  'Café Teatro Rayuela, Café Teatro Rayuela',
  'music',
  '2026-06-06 18:00:00+00',
  '2026-06-06 20:00:00+00',
  team_id, 'upcoming', 'lagenda:41757'
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['music'])
  FROM events WHERE external_id = 'lagenda:41757'
ON CONFLICT DO NOTHING;

-- Encuentro parrandero [lagenda:42253]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id) VALUES (
  gen_random_uuid(),
  'Encuentro parrandero',
  'II Encuentro Parrandero de Mayores de Garachico y una merienda comunitaria, para compartir canciones, tradiciones y buenos momentos en comunidad.',
  40.946454, -4.117123,
  'Antiguo Convento de San Francisco, Antiguo Convento de San Francisco',
  'music',
  '2026-06-06 18:00:00+00',
  '2026-06-06 20:00:00+00',
  team_id, 'upcoming', 'lagenda:42253'
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['music'])
  FROM events WHERE external_id = 'lagenda:42253'
ON CONFLICT DO NOTHING;

-- Elton John - Tribute Show [lagenda:41771]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id) VALUES (
  gen_random_uuid(),
  'Elton John - Tribute Show',
  'Experimenta en vivo todos los grandes éxitos de Elton John con este espectacular homenaje al icónico artista británico. Música en vivo, interpretación fiel al artista original y espectaculares juegos de luces.',
  28.291600, -16.629100,
  'Sala Timanfaya, Sala Timanfaya',
  'music',
  '2026-06-06 18:00:00+00',
  '2026-06-06 20:00:00+00',
  team_id, 'upcoming', 'lagenda:41771'
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['music'])
  FROM events WHERE external_id = 'lagenda:41771'
ON CONFLICT DO NOTHING;

-- ''Prendas, Trajes y Tipismo'' [lagenda:41405]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id) VALUES (
  gen_random_uuid(),
  '''Prendas, Trajes y Tipismo''',
  'Inauguración de la Exposición ''Prendas, Trajes y Tipismo'' realizada por el Cabildo de Tenerife.',
  40.193553, -6.161993,
  'Casa de la Cultura  de Granadilla, Casa de la Cultura  de Granadilla',
  'music',
  '2026-05-31 18:00:00+00',
  '2026-05-31 20:00:00+00',
  team_id, 'upcoming', 'lagenda:41405'
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['music'])
  FROM events WHERE external_id = 'lagenda:41405'
ON CONFLICT DO NOTHING;

-- ''Notas al pie'' [lagenda:41518]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id) VALUES (
  gen_random_uuid(),
  '''Notas al pie''',
  'El museo TEA Tenerife Espacio de las Artes inaugura la exposición ''Notas al pie'', el nuevo proyecto de Cabello/Carceller (Helena Cabello, París, 1963/Carceller, Madrid, 1964), que propone releer la historia desde sus márgenes, poniendo el foco en aquello que quedó fuera del relato oficial.',
  28.291600, -16.629100,
  'TEA Tenerife Espacio de las Artes, TEA Tenerife Espacio de las Artes',
  'music',
  '2026-07-05 18:00:00+00',
  '2026-07-05 20:00:00+00',
  team_id, 'upcoming', 'lagenda:41518'
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['music'])
  FROM events WHERE external_id = 'lagenda:41518'
ON CONFLICT DO NOTHING;

-- ''Rita'' [lagenda:41524]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id) VALUES (
  gen_random_uuid(),
  '''Rita''',
  'Los lienzos de Idaira del Castillo son enormes. Los hace ella misma. Va cosiendo sábanas, telas, manteles, ropa y demás restos de un naufragio.',
  43.337364, -1.837040,
  'Artizar, Artizar',
  'music',
  '2026-05-30 18:00:00+00',
  '2026-05-30 20:00:00+00',
  team_id, 'upcoming', 'lagenda:41524'
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['music'])
  FROM events WHERE external_id = 'lagenda:41524'
ON CONFLICT DO NOTHING;

-- ''Sobre la carne, en el vacío'' [lagenda:41614]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id) VALUES (
  gen_random_uuid(),
  '''Sobre la carne, en el vacío''',
  'El trabajo de este creador emergente propone entender la pintura no como una superficie estática, sino como un organismo en constante tensión entre lo físico y lo conceptual.',
  28.291600, -16.629100,
  'Sala  Arte Contemporáneo del Gobierno de Canarias, Sala  Arte Contemporáneo del Gobierno de Canarias',
  'music',
  '2026-06-26 18:00:00+00',
  '2026-06-26 20:00:00+00',
  team_id, 'upcoming', 'lagenda:41614'
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['music'])
  FROM events WHERE external_id = 'lagenda:41614'
ON CONFLICT DO NOTHING;

-- ''Marine Lucid Dream'' [lagenda:41781]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id) VALUES (
  gen_random_uuid(),
  '''Marine Lucid Dream''',
  'Con la presencia del autor y de la comisaria Anna Dimitrova, de Adda Gallery Ibiza. Una colaboración de Espacio Bronzo con Adda Gallery Ibiza.',
  28.291600, -16.629100,
  'Sala de Arte Bronzo, Sala de Arte Bronzo',
  'music',
  '2026-06-26 18:00:00+00',
  '2026-06-26 20:00:00+00',
  team_id, 'upcoming', 'lagenda:41781'
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['music'])
  FROM events WHERE external_id = 'lagenda:41781'
ON CONFLICT DO NOTHING;

-- Visitas al Templo Masónico de Santa Cruz de Tenerife [lagenda:39575]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id) VALUES (
  gen_random_uuid(),
  'Visitas al Templo Masónico de Santa Cruz de Tenerife',
  'El Templo Masónico de Santa Cruz de Tenerife acoge visitas libres y guiadas tras un proceso integral de rehabilitación orientado a su conservación y puesta en valor Más info y reserva online',
  28.467178, -16.250784,
  'Santa Cruz, Santa Cruz',
  'music',
  '2026-11-01 18:00:00+00',
  '2026-11-01 20:00:00+00',
  team_id, 'upcoming', 'lagenda:39575'
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['music'])
  FROM events WHERE external_id = 'lagenda:39575'
ON CONFLICT DO NOTHING;

-- ''Sombras y poemas'' [lagenda:40148]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id) VALUES (
  gen_random_uuid(),
  '''Sombras y poemas''',
  '''Sombras y poemas'', del escultor barcelonés Jaume Plensa expone  una muestra que reúne cerca de un centenar de obras, un recorrido artístico que aborda temas como la identidad, la espiritualidad, el lenguaje y la introspección a través de esculturas.',
  28.463600, -16.251800,
  'Espacio Cultural CajaCanarias Santa Cruz, Espacio Cultural CajaCanarias Santa Cruz',
  'music',
  '2026-06-13 18:00:00+00',
  '2026-06-13 20:00:00+00',
  team_id, 'upcoming', 'lagenda:40148'
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['music'])
  FROM events WHERE external_id = 'lagenda:40148'
ON CONFLICT DO NOTHING;

-- Murales en los Cristianos [lagenda:40394]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id) VALUES (
  gen_random_uuid(),
  'Murales en los Cristianos',
  'Creación de muestras artísticas permanentes que contribuyen a mejorar la estética urbana y a poner en valor las tradiciones del municipio.',
  28.052969, -16.713820,
  'Centro Cultural Los Cristianos, Centro Cultural Los Cristianos',
  'music',
  '2026-12-31 18:00:00+00',
  '2026-12-31 20:00:00+00',
  team_id, 'upcoming', 'lagenda:40394'
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['music'])
  FROM events WHERE external_id = 'lagenda:40394'
ON CONFLICT DO NOTHING;

-- ''Estancias Imaginadas III'' [lagenda:40499]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id) VALUES (
  gen_random_uuid(),
  '''Estancias Imaginadas III''',
  'Tercera muestra permanente del museo LM Arte Colección con el título Estancias Imaginadas III.  La muestra propone un recorrido por la historia de la casa a través de sus estancias, estableciendo un diálogo entre el patrimonio arquitectónico y una selección de los fondos del museo mediante un imaginario artístico crítico y diverso.',
  28.291600, -16.629100,
  'LM arte colección, LM arte colección',
  'music',
  '2027-12-31 18:00:00+00',
  '2027-12-31 20:00:00+00',
  team_id, 'upcoming', 'lagenda:40499'
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['music'])
  FROM events WHERE external_id = 'lagenda:40499'
ON CONFLICT DO NOTHING;

-- ''Alguien recordará al gallotia auritae'' [lagenda:41121]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id) VALUES (
  gen_random_uuid(),
  '''Alguien recordará al gallotia auritae''',
  'El programa Identitaria Canarias impulsa el documental "Los oficios de vivir: tradición y trabajo en los paisajes culturales urbanos de Canarias" sobre diversos oficios tradicionales del archipiélago en su contexto urbano, resaltando su valor cultural, histórico y social.',
  41.883107, 2.243152,
  'Online, Online',
  'music',
  '2026-12-31 18:00:00+00',
  '2026-12-31 20:00:00+00',
  team_id, 'upcoming', 'lagenda:41121'
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['music'])
  FROM events WHERE external_id = 'lagenda:41121'
ON CONFLICT DO NOTHING;

-- ‘Dokoupil. Pintura abstracta’ [lagenda:41106]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id) VALUES (
  gen_random_uuid(),
  '‘Dokoupil. Pintura abstracta’',
  'La exposición ‘Dokoupil. Pintura abstracta’, está integrada por una veintena de piezas de gran formato realizadas por Jiri Dokoupil con pompas de jabón, una técnica pictórica que inventó el propio artista checo y que lleva perfeccionando desde hace más de tres décadas',
  28.490777, -16.317394,
  'Instituto Cabrera Pinto, Instituto Cabrera Pinto',
  'music',
  '2026-05-31 18:00:00+00',
  '2026-05-31 20:00:00+00',
  team_id, 'upcoming', 'lagenda:41106'
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['music'])
  FROM events WHERE external_id = 'lagenda:41106'
ON CONFLICT DO NOTHING;

-- Cándido Camacho ''Ritos del deseo'' [lagenda:41161]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id) VALUES (
  gen_random_uuid(),
  'Cándido Camacho ''Ritos del deseo''',
  'Esta exposición dedicada al artista palmero Cándido Camacho (1951–1992) propone una revisión de su producción y responde a la necesidad de ofrecer una lectura actualizada de la trayectoria de un creador que contribuyó de forma significativa al desarrollo del arte contemporáneo en Canarias, pero que en las últimas décadas ha quedado desplazado hacia los márgenes.',
  28.291600, -16.629100,
  'TEA Tenerife Espacio de las Artes, TEA Tenerife Espacio de las Artes',
  'music',
  '2026-06-14 18:00:00+00',
  '2026-06-14 20:00:00+00',
  team_id, 'upcoming', 'lagenda:41161'
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['music'])
  FROM events WHERE external_id = 'lagenda:41161'
ON CONFLICT DO NOTHING;

-- ''Gráfica de la Conca'' [lagenda:41385]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id) VALUES (
  gen_random_uuid(),
  '''Gráfica de la Conca''',
  '''Gráfica de la Conca'' reúne una selección de obra gráfica procedente de los antiguos fondos de la histórica Sala Conca. A través de grabados, litografías, serigrafías, múltiples y libros de artista, la exposición muestra la riqueza técnica y la diversidad de lenguajes que atravesaron aquel tiempo, desde la abstracción y el informalismo hasta la poesía visual y la experimentación conceptual.',
  28.291600, -16.629100,
  'LM arte colección, LM arte colección',
  'music',
  '2026-06-06 18:00:00+00',
  '2026-06-06 20:00:00+00',
  team_id, 'upcoming', 'lagenda:41385'
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['music'])
  FROM events WHERE external_id = 'lagenda:41385'
ON CONFLICT DO NOTHING;

-- ''Ramón Gaya. La realidad salvada'' [lagenda:41790]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id) VALUES (
  gen_random_uuid(),
  '''Ramón Gaya. La realidad salvada''',
  'La muestra ''Ramón Gaya. La realidad salvada'',  con un amplio programa de actividades paralelas, ofrece una representativa selección de obras de las diferentes etapas de la trayectoria artística del pintor, realizadas entre 1923 y 2003.',
  28.291600, -16.629100,
  'Fundación Cristino de Vera-Espacio Cultural CajaCanarias, Fundación Cristino de Vera-Espacio Cultural CajaCanarias',
  'music',
  '2026-07-25 18:00:00+00',
  '2026-07-25 20:00:00+00',
  team_id, 'upcoming', 'lagenda:41790'
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['music'])
  FROM events WHERE external_id = 'lagenda:41790'
ON CONFLICT DO NOTHING;

-- ''Desapego'' [lagenda:42251]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id) VALUES (
  gen_random_uuid(),
  '''Desapego''',
  'Exposición que habita ese espacio extraño entre lo que soltamos y lo que todavía permanece. A través de la pintura, instalación, fotografía y otros lenguajes contemporáneos, un grupo de jóvenes artistas explora los vínculos con la identidad, la memoria, los objetos y las emociones que nos construyen.',
  28.485798, -16.312900,
  'Convento Santo Domingo La Laguna, Convento Santo Domingo La Laguna',
  'music',
  '2026-06-13 18:00:00+00',
  '2026-06-13 20:00:00+00',
  team_id, 'upcoming', 'lagenda:42251'
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['music'])
  FROM events WHERE external_id = 'lagenda:42251'
ON CONFLICT DO NOTHING;

-- Dinosaurios Live en Adeje [lagenda:42099]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id) VALUES (
  gen_random_uuid(),
  'Dinosaurios Live en Adeje',
  'Una experiencia divertida, educativa e inmersiva para toda la familia, donde grandes y pequeños pueden viajar al pasado y descubrir el fascinante mundo de los dinosaurios. Reserva entradas online',
  28.086983, -16.735797,
  'Costa Adeje, Costa Adeje',
  'music',
  '2026-05-31 18:00:00+00',
  '2026-05-31 20:00:00+00',
  team_id, 'upcoming', 'lagenda:42099'
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['music'])
  FROM events WHERE external_id = 'lagenda:42099'
ON CONFLICT DO NOTHING;

-- ''The not so still life II'' [lagenda:42121]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id) VALUES (
  gen_random_uuid(),
  '''The not so still life II''',
  'Un acto de inauguración de la exposición ''The not so still life II'' de la mano de Celestino Mesa',
  28.291600, -16.629100,
  'Desván Blanco Espacio Cultural, Desván Blanco Espacio Cultural',
  'music',
  '2026-06-12 18:00:00+00',
  '2026-06-12 20:00:00+00',
  team_id, 'upcoming', 'lagenda:42121'
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['music'])
  FROM events WHERE external_id = 'lagenda:42121'
ON CONFLICT DO NOTHING;

-- ''Sueños'' [lagenda:42268]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id) VALUES (
  gen_random_uuid(),
  '''Sueños''',
  'A través de retratos de personas de distintas edades, procedencias y condiciones vitales, el artista explora el universo emocional y humano que se esconde tras los anhelos individuales.',
  28.465490, -16.250776,
  'La Recova Centro de Arte, La Recova Centro de Arte',
  'music',
  '2026-06-28 18:00:00+00',
  '2026-06-28 20:00:00+00',
  team_id, 'upcoming', 'lagenda:42268'
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['music'])
  FROM events WHERE external_id = 'lagenda:42268'
ON CONFLICT DO NOTHING;

-- ''Casi Alguien'' [lagenda:42205]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id) VALUES (
  gen_random_uuid(),
  '''Casi Alguien''',
  'Teresa Correa, Pedro González, Moneiba Lemes, Fernando Martín Godoy, Cristina Temes. En esta muestra, el retrato aparece no como una afirmación, sino como una pregunta abierta sobre quiénes somos y cómo nos representamos.',
  28.291600, -16.629100,
  'Bibli, Bibli',
  'music',
  '2026-07-31 18:00:00+00',
  '2026-07-31 20:00:00+00',
  team_id, 'upcoming', 'lagenda:42205'
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['music'])
  FROM events WHERE external_id = 'lagenda:42205'
ON CONFLICT DO NOTHING;

-- ''Desbordes y tangentes'' [lagenda:42358]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id) VALUES (
  gen_random_uuid(),
  '''Desbordes y tangentes''',
  'La exposición plantea un recorrido por distintas aproximaciones al dibujo contemporáneo, entendido ya no como una práctica limitada al papel y a lo bidimensional, sino como un lenguaje capaz de ocupar el espacio, expandirse hacia lo instalativo, lo performático o lo audiovisual, y dialogar con el cuerpo y la arquitectura.',
  28.100484, -15.416912,
  'Fundación Mapfre Canarias, Fundación Mapfre Canarias',
  'music',
  '2026-07-31 18:00:00+00',
  '2026-07-31 20:00:00+00',
  team_id, 'upcoming', 'lagenda:42358'
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['music'])
  FROM events WHERE external_id = 'lagenda:42358'
ON CONFLICT DO NOTHING;

-- ''Marine Lucid Dream'' [lagenda:42357]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id) VALUES (
  gen_random_uuid(),
  '''Marine Lucid Dream''',
  'Esculturas, dibujos a grafiti y pinturas elaboradas en Tenerife por el autor ucraniano Aleksei Bordusov, conocido internacionalmente como Aec Interesni Kazki. Una exposición sobre la libertad de la conciencia dentro de un mundo que ofrece muy poca de ella.',
  28.291600, -16.629100,
  'Sala de Arte Bronzo, Sala de Arte Bronzo',
  'music',
  '2026-06-26 18:00:00+00',
  '2026-06-26 20:00:00+00',
  team_id, 'upcoming', 'lagenda:42357'
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['music'])
  FROM events WHERE external_id = 'lagenda:42357'
ON CONFLICT DO NOTHING;

-- ''Donde cantan los pelícanos'' [lagenda:42352]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id) VALUES (
  gen_random_uuid(),
  '''Donde cantan los pelícanos''',
  'Instalación de Carlos Nicanor que explora vínculos entre orillas atlánticas mediante islas flotantes y una reflexión crítica sobre la idea de paraíso. El proyecto conecta experiencias migratorias, memoria y territorio. La obra del escultor destaca por su intensidad poética y su investigación sobre formas, procesos y relaciones entre arte y ciudadanía.',
  28.457310, -16.256110,
  'Espacio Cultural El Tanque, Espacio Cultural El Tanque',
  'music',
  '2026-08-10 18:00:00+00',
  '2026-08-10 20:00:00+00',
  team_id, 'upcoming', 'lagenda:42352'
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['music'])
  FROM events WHERE external_id = 'lagenda:42352'
ON CONFLICT DO NOTHING;

-- El Niño Sombra - Encuentros en el Mar 2026 [lagenda:41910]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id) VALUES (
  gen_random_uuid(),
  'El Niño Sombra - Encuentros en el Mar 2026',
  'La XXII edición del Festival Encuentros en el mar. Transculturalidades ofrece en Los Silos la exposición de El Niño Sombra durante el mes de junio',
  28.365223, -16.817377,
  'Exconvento de San Sebastián, Exconvento de San Sebastián',
  'music',
  '2026-06-28 18:00:00+00',
  '2026-06-28 20:00:00+00',
  team_id, 'upcoming', 'lagenda:41910'
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['music'])
  FROM events WHERE external_id = 'lagenda:41910'
ON CONFLICT DO NOTHING;

END $$;