-- Auto-generated by event-sync on 2026-06-02
-- Scraped range: 2026-06-02 → 2026-06-23
-- Run manually in Supabase Dashboard → SQL Editor
-- Idempotent: ON CONFLICT (external_id) DO NOTHING skips duplicates
-- Requires migration 20260530_add_external_id.sql

DO $$
DECLARE
  team_id uuid := 'b864b6bf-4282-4644-ab8f-b17b661b7841';
BEGIN

-- Actividad de junio en la Librería del Cabildo [lagenda:42417]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id, photos) VALUES (
  gen_random_uuid(),
  'Actividad de junio en la Librería del Cabildo',
  'La Librería del Cabildo, consolida su programación cultural con una agenda de actividades para el mes de junio que incluirá firmas de libros, presentaciones literarias y del club de lectura  y un homenaje al escritor y periodista Alfonso García-Ramos.',
  28.104881, -15.416649,
  'Librería del Cabildo, Librería del Cabildo',
  'art',
  '2026-06-02 18:00:00+00',
  '2026-06-02 20:00:00+00',
  team_id, 'upcoming', 'lagenda:42417', ARRAY['https://s3-eu-west-1.amazonaws.com/beta.lagenda/programacion/libreria-del-cabildo.jpg']::text[]
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['art'])
  FROM events WHERE external_id = 'lagenda:42417'
ON CONFLICT DO NOTHING;

-- Fiestas Virgen de Las Nieves 2026 - Adeje [lagenda:42430]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id, photos) VALUES (
  gen_random_uuid(),
  'Fiestas Virgen de Las Nieves 2026 - Adeje',
  'Las celebraciones de las Fiestas de la Virgen de Las Nieves 2026 en Adeje incluyen juegos tradicionales, encuentros comunitarios, desfiles, festivales, música en vivo, galas con actuaciones variadas, actividades infantiles, eventos deportivos, comidas populares y bailes. Se combinan tradiciones, espectáculos y convivencia vecinal para disfrutar en familia.',
  28.139440, -16.739456,
  'Adeje, Adeje',
  'culture',
  '2026-06-02 18:00:00+00',
  '2026-06-02 20:00:00+00',
  team_id, 'upcoming', 'lagenda:42430', ARRAY['https://s3-eu-west-1.amazonaws.com/beta.lagenda/programacion/virgen-nieves-adeje-2026.jpg']::text[]
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['culture', 'dance'])
  FROM events WHERE external_id = 'lagenda:42430'
ON CONFLICT DO NOTHING;

-- ''Navegarte'' [lagenda:42278]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id, photos) VALUES (
  gen_random_uuid(),
  '''Navegarte''',
  'Ruta teatral que se representarán a bordo del emblemático Correíllo La Palma de la mano de Sergio Miranda y Jaster Luis',
  28.467178, -16.250784,
  'Santa Cruz, Santa Cruz',
  'culture',
  '2026-06-02 18:00:00+00',
  '2026-06-02 20:00:00+00',
  team_id, 'upcoming', 'lagenda:42278', ARRAY['https://s3-eu-west-1.amazonaws.com/beta.lagenda/programacion/navegarte.jpg']::text[]
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['art'])
  FROM events WHERE external_id = 'lagenda:42278'
ON CONFLICT DO NOTHING;

-- Suma Festival 2026 [lagenda:42288]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id, photos) VALUES (
  gen_random_uuid(),
  'Suma Festival 2026',
  'VII Edición de Suma Festival, Santa Úrsula Música y Arte, con una variada selección de artistas, talleres y actuaciones en vivo. Álvaro Gacía, Abubukaka, Pieles, Anaé, Darío López.',
  28.425142, -16.491538,
  'Municipio de Santa Úrsula, Municipio de Santa Úrsula',
  'culture',
  '2026-06-02 18:00:00+00',
  '2026-06-02 20:00:00+00',
  team_id, 'upcoming', 'lagenda:42288', ARRAY['https://s3-eu-west-1.amazonaws.com/beta.lagenda/programacion/suma-festival.jpg']::text[]
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['culture', 'dance'])
  FROM events WHERE external_id = 'lagenda:42288'
ON CONFLICT DO NOTHING;

-- Dúo del Valle [lagenda:41697]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id, photos) VALUES (
  gen_random_uuid(),
  'Dúo del Valle',
  'Recital del Dúo del Valle, a cargo de los hermanos Víctor y Luis del Valle, quienes interpretarán a dos pianos el programa ''El jardín de lo imposible'' dentro de los conciertos de piano del Ciclo de Cámara de Auditorio de Tenerife',
  28.456074, -16.251243,
  'Auditorio de Tenerife Adán Martín, Auditorio de Tenerife Adán Martín',
  'music',
  '2026-06-02 18:00:00+00',
  '2026-06-02 20:00:00+00',
  team_id, 'upcoming', 'lagenda:41697', ARRAY['https://s3-eu-west-1.amazonaws.com/beta.lagenda/programacion/duo-del-valler.jpg']::text[]
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['music'])
  FROM events WHERE external_id = 'lagenda:41697'
ON CONFLICT DO NOTHING;

-- Fiestas de Mayo en Los Realejos 2026 [lagenda:41839]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id, photos) VALUES (
  gen_random_uuid(),
  'Fiestas de Mayo en Los Realejos 2026',
  'Llega mayo, el mes en el que Los Realejos se une con más fuerza que nunca, un tiempo en el que la devoción, la tradición y la alegría se entrelazan para dar forma a unas fiestas que nacen del corazón de Los Realejos.',
  28.350311, -16.584952,
  'Los Realejos, Los Realejos',
  'culture',
  '2026-06-02 18:00:00+00',
  '2026-06-02 20:00:00+00',
  team_id, 'upcoming', 'lagenda:41839', ARRAY['https://s3-eu-west-1.amazonaws.com/beta.lagenda/programacion/fiestas_de_mayo_los_realejos.jpg']::text[]
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['culture', 'dance'])
  FROM events WHERE external_id = 'lagenda:41839'
ON CONFLICT DO NOTHING;

-- Le Cirque Zoppis [lagenda:42103]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id, photos) VALUES (
  gen_random_uuid(),
  'Le Cirque Zoppis',
  'Una experiencia envolvente donde una esfera luminosa, símbolo del sueño de un niño, nos guía a través de un universo mágico lleno de emoción, fantasía y momentos que te dejarán sin palabras.',
  28.487048, -16.314040,
  'Municipio de San Cristóbal de La Laguna, Municipio de San Cristóbal de La Laguna',
  'family',
  '2026-06-03 18:00:00+00',
  '2026-06-03 20:00:00+00',
  team_id, 'upcoming', 'lagenda:42103', ARRAY['https://s3-eu-west-1.amazonaws.com/beta.lagenda/programacion/circo-zoppis.jpg']::text[]
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['family'])
  FROM events WHERE external_id = 'lagenda:42103'
ON CONFLICT DO NOTHING;

-- Rutas ''La Letra Esmeralda'' [lagenda:42118]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id, photos) VALUES (
  gen_random_uuid(),
  'Rutas ''La Letra Esmeralda''',
  'El Centro de Documentación de Canarias y América organiza las rutas gratuitas ''La Letra Esmeralda'', en Santa Cruz de Tenerife y La Laguna. Los participantes vivirán una experiencia única visitando lugares emblemáticos relacionados con la vida de Esmeralda Cervantes',
  37.372751, -5.947118,
  'C.C. Meridiano, C.C. Meridiano',
  'culture',
  '2026-06-03 18:00:00+00',
  '2026-06-03 20:00:00+00',
  team_id, 'upcoming', 'lagenda:42118', ARRAY['https://s3-eu-west-1.amazonaws.com/beta.lagenda/programacion/la-letra-esmeralda.gif']::text[]
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['culture'])
  FROM events WHERE external_id = 'lagenda:42118'
ON CONFLICT DO NOTHING;

-- Swing Hits [lagenda:42173]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id, photos) VALUES (
  gen_random_uuid(),
  'Swing Hits',
  'Un recorrido por el repertorio de swing y de soul en formato Big Band',
  28.527000, -16.338300,
  'Teatro Unión Tejina, Teatro Unión Tejina',
  'music',
  '2026-06-03 18:00:00+00',
  '2026-06-03 20:00:00+00',
  team_id, 'upcoming', 'lagenda:42173', ARRAY['https://s3-eu-west-1.amazonaws.com/beta.lagenda/programacion/1_2.png']::text[]
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['music'])
  FROM events WHERE external_id = 'lagenda:42173'
ON CONFLICT DO NOTHING;

-- ''Tres noches en Ítaca'' - Primavera en la Fundación 2026 [lagenda:40529]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id, photos) VALUES (
  gen_random_uuid(),
  '''Tres noches en Ítaca'' - Primavera en la Fundación 2026',
  'Tragicomedia de Alberto Conejero interpretada por Marta Nieto, Cecilia Freire y Amaia Lizarralde, ambientada en una casa frente al mar en Ítaca donde tres hermanas afrontan el duelo por su madre y revisitan su pasado desde la memoria, la luz y la imaginación. La obra, profundiza en las relaciones entre las hermanas Ariadna, Penélope y Elena, en el legado de una madre excéntrica y en las preguntas sobre cómo renacer, reescribir la propia vida y mantener vivas las Humanidades en tiempos inciertos.',
  28.463600, -16.251800,
  'Espacio Cultural CajaCanarias Santa Cruz, Espacio Cultural CajaCanarias Santa Cruz',
  'culture',
  '2026-06-03 18:00:00+00',
  '2026-06-03 20:00:00+00',
  team_id, 'upcoming', 'lagenda:40529', ARRAY['https://s3-eu-west-1.amazonaws.com/beta.lagenda/programacion/tres-noches-itaca.jpg']::text[]
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['art'])
  FROM events WHERE external_id = 'lagenda:40529'
ON CONFLICT DO NOTHING;

-- Taller ''La magia de las letras'' [lagenda:41998]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id, photos) VALUES (
  gen_random_uuid(),
  'Taller ''La magia de las letras''',
  '''La magia de las letras'' es un taller impartido por el escritor Víctor Conde centrado en la narrativa clásica. El alumnado deberá redactar sus propios textos y posteriormente, se realizará una puesta en común con lecturas y correcciones.',
  28.104881, -15.416649,
  'Librería del Cabildo, Librería del Cabildo',
  'art',
  '2026-06-03 18:00:00+00',
  '2026-06-03 20:00:00+00',
  team_id, 'upcoming', 'lagenda:41998', ARRAY['https://s3-eu-west-1.amazonaws.com/beta.lagenda/programacion/libreria-del-cabildo.jpg']::text[]
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['art'])
  FROM events WHERE external_id = 'lagenda:41998'
ON CONFLICT DO NOTHING;

-- ''Orlando, mi biografía política'' [lagenda:42436]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id, photos) VALUES (
  gen_random_uuid(),
  '''Orlando, mi biografía política''',
  'En 1928, Virginia Woolf publica Orlando, la primera novela en la que el personaje principal cambia de sexo en medio de la historia. Un siglo más tarde, el filósofo Paul B. Preciado decide escribirle una carta a Virginia Woolf: su Orlando ha salido de la ficción y lleva una vida que jamás habría imaginado.',
  41.128143, 1.206468,
  'Espacio La Granja, Espacio La Granja',
  'culture',
  '2026-06-04 18:00:00+00',
  '2026-06-04 20:00:00+00',
  team_id, 'upcoming', 'lagenda:42436', ARRAY['https://s3-eu-west-1.amazonaws.com/beta.lagenda/programacion/orlando-paul-b-preciado.jpg']::text[]
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['art'])
  FROM events WHERE external_id = 'lagenda:42436'
ON CONFLICT DO NOTHING;

-- Jaleo en la Plaza - FICMEC 2026 [lagenda:42384]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id, photos) VALUES (
  gen_random_uuid(),
  'Jaleo en la Plaza - FICMEC 2026',
  'El Festival Internacional de Cine Medioambiental de Canarias (FICMEC) ofrece en 2026 una ambiciosa propuesta que va más allá de la gran pantalla. Bajo el sello de ‘Jaleo en la Plaza’, el festival ha diseñado una completa programación cultural y familiar que llenará de vida los espacios públicos de Garachico e Icod de los Vinos',
  28.293578, -16.621447,
  'Tenerife, Tenerife',
  'culture',
  '2026-06-04 18:00:00+00',
  '2026-06-04 20:00:00+00',
  team_id, 'upcoming', 'lagenda:42384', ARRAY['https://s3-eu-west-1.amazonaws.com/beta.lagenda/programacion/ficmec2026.jpg']::text[]
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['art'])
  FROM events WHERE external_id = 'lagenda:42384'
ON CONFLICT DO NOTHING;

-- Just Lío [lagenda:42408]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id, photos) VALUES (
  gen_random_uuid(),
  'Just Lío',
  'La nueva experiencia de tardeo de Palapa Beach Club. Cócteles frente al mar, DJs en directo, buena música y el mejor ambiente para alargar la tarde hasta la puesta de sol. Un plan pensado para disfrutar, desconectar y dejarse llevar. Porque a veces una copa lleva a otra, y la tarde acaba liándose.',
  28.060197, -16.731053,
  'Playa de Las Américas, Playa de Las Américas',
  'music',
  '2026-06-04 18:00:00+00',
  '2026-06-04 20:00:00+00',
  team_id, 'upcoming', 'lagenda:42408', ARRAY['https://s3-eu-west-1.amazonaws.com/beta.lagenda/programacion/palapa-beach-club.jpg']::text[]
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['music'])
  FROM events WHERE external_id = 'lagenda:42408'
ON CONFLICT DO NOTHING;

-- Semana Internacional de la Moda de Tenerife 2026 [lagenda:42237]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id, photos) VALUES (
  gen_random_uuid(),
  'Semana Internacional de la Moda de Tenerife 2026',
  'La Semana Internacional de la Moda de Tenerife regresa en 2026 con una apuesta dedicada por las tendencias urbanas',
  28.454605, -16.257730,
  'Recinto Ferial, Recinto Ferial',
  'culture',
  '2026-06-04 18:00:00+00',
  '2026-06-04 20:00:00+00',
  team_id, 'upcoming', 'lagenda:42237', ARRAY['https://s3-eu-west-1.amazonaws.com/beta.lagenda/lugares/recinto_ferial_0.jpg']::text[]
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['culture'])
  FROM events WHERE external_id = 'lagenda:42237'
ON CONFLICT DO NOTHING;

-- Programa 28 FICMEC - Icod de los Vinos [lagenda:42297]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id, photos) VALUES (
  gen_random_uuid(),
  'Programa 28 FICMEC - Icod de los Vinos',
  'FICMEC, el Festival de Cine Medioambiental de Canarias divide su vigésima octava edición entre Garachico e Icod de Los Vinos con sus históricas secciones oficiales de cine documental y ficción, animación, y las ya consagradas Vulcanalia, Jugando en Verde o Fotosíntesis, además de una envidiable oferta educativa y cultural',
  28.366453, -16.721122,
  'Icod, Icod',
  'culture',
  '2026-06-04 18:00:00+00',
  '2026-06-04 20:00:00+00',
  team_id, 'upcoming', 'lagenda:42297', ARRAY['https://s3-eu-west-1.amazonaws.com/beta.lagenda/programacion/ficmec2026-2.jpg']::text[]
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['art'])
  FROM events WHERE external_id = 'lagenda:42297'
ON CONFLICT DO NOTHING;

-- Ballet Stars Gala [lagenda:41716]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id, photos) VALUES (
  gen_random_uuid(),
  'Ballet Stars Gala',
  'En esta noche mágica, se podrá disfrutar de los más impresionantes solos de algunos de los ballets más queridos de todos los tiempos; ''El Lago de los Cisnes'', ''Don Quijote'', ''Raymonda'' o ''El Corsario'', entre otros. Una oportunidad única de disfrutar del ballet clásico en su máxima expresión.',
  28.478868, -16.436560,
  'Teatro El Sauzal, Teatro El Sauzal',
  'culture',
  '2026-06-04 18:00:00+00',
  '2026-06-04 20:00:00+00',
  team_id, 'upcoming', 'lagenda:41716', ARRAY['https://s3-eu-west-1.amazonaws.com/beta.lagenda/programacion/ballet-stars-gala.jpg']::text[]
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['art'])
  FROM events WHERE external_id = 'lagenda:41716'
ON CONFLICT DO NOTHING;

-- ''Cada loco con su tema'' [lagenda:42100]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id, photos) VALUES (
  gen_random_uuid(),
  '''Cada loco con su tema''',
  'Una comedia fresca, ágil y para todos los públicos que busca provocar carcajadas inmediatas con personajes entrañables y delirantes',
  28.291600, -16.629100,
  'L''Incanto, L''Incanto',
  'culture',
  '2026-06-04 18:00:00+00',
  '2026-06-04 20:00:00+00',
  team_id, 'upcoming', 'lagenda:42100', ARRAY['https://s3-eu-west-1.amazonaws.com/beta.lagenda/programacion/cada-loco-con-su-tema.jpg']::text[]
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['art'])
  FROM events WHERE external_id = 'lagenda:42100'
ON CONFLICT DO NOTHING;

-- ''Yo,tu,ella'' [lagenda:42101]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id, photos) VALUES (
  gen_random_uuid(),
  '''Yo,tu,ella''',
  'Una comedia confesional escrita por Mónica Montañés y dirigida por Crisol Carabal. Tres mujeres emprenden un inesperado viaje emocional entre confesiones, risas y reconciliación personal.',
  28.291600, -16.629100,
  'L''Incanto, L''Incanto',
  'culture',
  '2026-06-05 18:00:00+00',
  '2026-06-05 20:00:00+00',
  team_id, 'upcoming', 'lagenda:42101', ARRAY['https://s3-eu-west-1.amazonaws.com/beta.lagenda/programacion/yotuella.jpg']::text[]
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['art'])
  FROM events WHERE external_id = 'lagenda:42101'
ON CONFLICT DO NOTHING;

-- ''El amigo silencioso'' [lagenda:42391]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id, photos) VALUES (
  gen_random_uuid(),
  '''El amigo silencioso''',
  'Tres historias ambientadas en épocas distintas que se suceden a los pies de un un ginkgo centenario. Este árbol, testigo silencioso, ha observado durante más de un siglo los tranquilos ritmos de la transformación a lo largo de tres vidas humanas. ''El amigo silencioso'' de Ildikó Enyedi fué Ganadora del Premio del Jurado de la Crítica Internacional en el Festival de Cine de Venecia y de la Espiga de Plata en la Seminci',
  28.291600, -16.629100,
  'TEA Tenerife Espacio de las Artes, TEA Tenerife Espacio de las Artes',
  'culture',
  '2026-06-05 18:00:00+00',
  '2026-06-05 20:00:00+00',
  team_id, 'upcoming', 'lagenda:42391', ARRAY['https://s3-eu-west-1.amazonaws.com/beta.lagenda/programacion/el-amigo-silencioso.jpg']::text[]
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['art'])
  FROM events WHERE external_id = 'lagenda:42391'
ON CONFLICT DO NOTHING;

-- Paredes - Marichal - Glez Torres [lagenda:42164]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id, photos) VALUES (
  gen_random_uuid(),
  'Paredes - Marichal - Glez Torres',
  'Tres trayectorias, tres lenguajes, un único momento irrepetible. David Paredes , Ricardo Marichal y Fran Glez Torres se encuentran por primera vez sobre el escenario para explorar sin mapa: improvisación pura, cruce de escenas y diálogo en tiempo real.',
  28.291600, -16.629100,
  'Asociación Cultural Equipo PARA, Asociación Cultural Equipo PARA',
  'music',
  '2026-06-05 18:00:00+00',
  '2026-06-05 20:00:00+00',
  team_id, 'upcoming', 'lagenda:42164', ARRAY['https://s3-eu-west-1.amazonaws.com/beta.lagenda/programacion/equipopara.jpg']::text[]
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['music'])
  FROM events WHERE external_id = 'lagenda:42164'
ON CONFLICT DO NOTHING;

-- ''Tras la estela de Shackleton'' [lagenda:42272]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id, photos) VALUES (
  gen_random_uuid(),
  '''Tras la estela de Shackleton''',
  'Proyección del documental ''Tras la estela de Shackleton'' donde el alpinista y divulgador Juan Diego Amador nos cuenta su viaje a la Ántartida, siguiendo los pasos del célebre aventurero Sir Ernest Shackleton. Una dramática e histórica experiencia de supervivencia que las personas asistentes podrán compartir y desgranar junto al en un coloquio posterior.',
  28.467178, -16.250784,
  'Santa Cruz, Santa Cruz',
  'culture',
  '2026-06-05 18:00:00+00',
  '2026-06-05 20:00:00+00',
  team_id, 'upcoming', 'lagenda:42272', ARRAY['https://s3-eu-west-1.amazonaws.com/beta.lagenda/programacion/tras-la-estela-de-shackleton_0.jpg']::text[]
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['art'])
  FROM events WHERE external_id = 'lagenda:42272'
ON CONFLICT DO NOTHING;

-- La Bien Querida - Primavera en la Fundación 2026 [lagenda:40531]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id, photos) VALUES (
  gen_random_uuid(),
  'La Bien Querida - Primavera en la Fundación 2026',
  'La Bien Querida es el proyecto de Ana Fernández-Villaverde, figura clave del pop alternativo español, cuyas canciones mezclan electrónica y pop con letras románticas y existenciales; desde ''Romancero'' hasta trabajos como ''Fiesta'', ''Ceremonia'', ''Fuego'' o ''Paprika'', la artista ha construido un universo sonoro muy personal',
  28.463600, -16.251800,
  'Espacio Cultural CajaCanarias Santa Cruz, Espacio Cultural CajaCanarias Santa Cruz',
  'music',
  '2026-06-05 18:00:00+00',
  '2026-06-05 20:00:00+00',
  team_id, 'upcoming', 'lagenda:40531', ARRAY['https://s3-eu-west-1.amazonaws.com/beta.lagenda/programacion/la-bien-querida.jpg']::text[]
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['music'])
  FROM events WHERE external_id = 'lagenda:40531'
ON CONFLICT DO NOTHING;

-- Luis Piedrahita [lagenda:41662]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id, photos) VALUES (
  gen_random_uuid(),
  'Luis Piedrahita',
  '''Apocalípticamente correcto'' es el nuevo show de Luis Piedrahita, un ingenioso monólogo sobre la libertad y el destino. Son temas delicados, pero Luis no teme a nada. El miedo espanta la risa y, de modo recíproco, la risa espanta al miedo.',
  28.489700, -16.318123,
  'Teatro Leal, Teatro Leal',
  'culture',
  '2026-06-05 18:00:00+00',
  '2026-06-05 20:00:00+00',
  team_id, 'upcoming', 'lagenda:41662', ARRAY['https://s3-eu-west-1.amazonaws.com/beta.lagenda/programacion/luis-piedrahita.jpg']::text[]
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['art'])
  FROM events WHERE external_id = 'lagenda:41662'
ON CONFLICT DO NOTHING;

-- Fiestas de Mayo 2026 Santa Cruz de Tenerife [lagenda:41682]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id, photos) VALUES (
  gen_random_uuid(),
  'Fiestas de Mayo 2026 Santa Cruz de Tenerife',
  'Santa Cruz de Tenerife ofrece para sus Fiestas de Mayo 2026 un amplio programa con más de un centenar de iniciativas culturales, artísticas, lúdicas y deportivas con motivo de las Fiestas Fundacionales de la capital',
  28.469929, -16.254557,
  'Municipio de Santa Cruz, Municipio de Santa Cruz',
  'culture',
  '2026-06-05 18:00:00+00',
  '2026-06-05 20:00:00+00',
  team_id, 'upcoming', 'lagenda:41682', ARRAY['https://s3-eu-west-1.amazonaws.com/beta.lagenda/programacion/fiestas-mayo-santa-cruz-tenerife-2026.jpg']::text[]
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['culture', 'dance'])
  FROM events WHERE external_id = 'lagenda:41682'
ON CONFLICT DO NOTHING;

-- Variaciones sobre Temas canarios - FMUC 2026 [lagenda:41694]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id, photos) VALUES (
  gen_random_uuid(),
  'Variaciones sobre Temas canarios - FMUC 2026',
  'El Festival de Música Contemporánea de Tenerife (FMUC), edición 2026, programa Variaciones sobre Temas canarios, una obra de estreno de Francis Hernández, pianista, compositor y director musical, considerado un músico ecléctico que ha alternado la música académica con la música popular. Este año, estrenará una nueva obra compuesta para esta edición del festival.',
  28.456074, -16.251243,
  'Auditorio de Tenerife Adán Martín, Auditorio de Tenerife Adán Martín',
  'culture',
  '2026-06-05 18:00:00+00',
  '2026-06-05 20:00:00+00',
  team_id, 'upcoming', 'lagenda:41694', ARRAY['https://s3-eu-west-1.amazonaws.com/beta.lagenda/programacion/fmuc-2026.jpg']::text[]
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['culture'])
  FROM events WHERE external_id = 'lagenda:41694'
ON CONFLICT DO NOTHING;

-- The Molotovs [lagenda:42294]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id, photos) VALUES (
  gen_random_uuid(),
  'The Molotovs',
  'El dúo británico de los hermanos Matt e Issey Cartlidge se acerca a Tenerife dentro de una envidiable gira que les lleva por todo el planeta',
  28.291600, -16.629100,
  'Aguere Espacio Cultural, Aguere Espacio Cultural',
  'music',
  '2026-06-05 18:00:00+00',
  '2026-06-05 20:00:00+00',
  team_id, 'upcoming', 'lagenda:42294', ARRAY['https://s3-eu-west-1.amazonaws.com/beta.lagenda/programacion/the-molotovs.jpg']::text[]
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['music'])
  FROM events WHERE external_id = 'lagenda:42294'
ON CONFLICT DO NOTHING;

-- Ballet Stars Gala [lagenda:41730]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id, photos) VALUES (
  gen_random_uuid(),
  'Ballet Stars Gala',
  'En esta noche mágica, se podrá disfrutar de los más impresionantes solos de algunos de los ballets más queridos de todos los tiempos; ''El Lago de los Cisnes'', ''Don Quijote'', ''Raymonda'' o ''El Corsario'', entre otros. Una oportunidad única de disfrutar del ballet clásico en su máxima expresión.',
  28.291600, -16.629100,
  'Auditorio Infanta Leonor, Auditorio Infanta Leonor',
  'culture',
  '2026-06-05 18:00:00+00',
  '2026-06-05 20:00:00+00',
  team_id, 'upcoming', 'lagenda:41730', ARRAY['https://s3-eu-west-1.amazonaws.com/beta.lagenda/programacion/ballet-stars-gala.jpg']::text[]
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['art'])
  FROM events WHERE external_id = 'lagenda:41730'
ON CONFLICT DO NOTHING;

-- Alex Janssen Trío [lagenda:42326]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id, photos) VALUES (
  gen_random_uuid(),
  'Alex Janssen Trío',
  'Concierto de jazz en el que disfrutaremos de envolventes melodías y pasajes improvisados a través de texturas, ritmos y armonías, que reflejan las influencias individuales de cada componente',
  28.291600, -16.629100,
  'Café Teatro Rayuela, Café Teatro Rayuela',
  'music',
  '2026-06-05 18:00:00+00',
  '2026-06-05 20:00:00+00',
  team_id, 'upcoming', 'lagenda:42326', ARRAY['https://s3-eu-west-1.amazonaws.com/beta.lagenda/programacion/alex-jansen.jpg']::text[]
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['music'])
  FROM events WHERE external_id = 'lagenda:42326'
ON CONFLICT DO NOTHING;

-- Baile de Magos La Orotava 2026 [lagenda:42338]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id, photos) VALUES (
  gen_random_uuid(),
  'Baile de Magos La Orotava 2026',
  'Jornada llena de actividad en las Fiestas de La Orotava 2026 con grandes bailes, tradición, orquesta y gastronomía popular',
  28.389883, -16.523569,
  'La Orotava, La Orotava',
  'culture',
  '2026-06-05 18:00:00+00',
  '2026-06-05 20:00:00+00',
  team_id, 'upcoming', 'lagenda:42338', ARRAY['https://s3-eu-west-1.amazonaws.com/beta.lagenda/programacion/orotava_0.jpg']::text[]
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['culture', 'dance'])
  FROM events WHERE external_id = 'lagenda:42338'
ON CONFLICT DO NOTHING;

-- ''La voracidad. Entre vampiros y zombies'' [lagenda:42366]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id, photos) VALUES (
  gen_random_uuid(),
  '''La voracidad. Entre vampiros y zombies''',
  'Aranza Coello realiza una residencia de investigación dramatúrgica en La Salita ''La voracidad (entre vampiros y zombies)''. Un encuentro donde jugar a compartir experiencias y visiones sobre el sector turístico. No es una charla, no es una clase, es un espacio donde exponer, de otra manera, nuestra mirada sobre el uso del territorio.',
  28.456074, -16.251243,
  'Auditorio de Tenerife Adán Martín, Auditorio de Tenerife Adán Martín',
  'culture',
  '2026-06-05 18:00:00+00',
  '2026-06-05 20:00:00+00',
  team_id, 'upcoming', 'lagenda:42366', ARRAY['https://s3-eu-west-1.amazonaws.com/beta.lagenda/programacion/aranza-coello-2026.jpg']::text[]
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['art'])
  FROM events WHERE external_id = 'lagenda:42366'
ON CONFLICT DO NOTHING;

-- Las Arañas del Neptuno [lagenda:42368]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id, photos) VALUES (
  gen_random_uuid(),
  'Las Arañas del Neptuno',
  'Junio llega con mucho oleaje a Santa Cruz de Tenerife, tanto que las olas llegarán hasta el escenario del Lone Star. Los chicos de Las Arañas del Neptuno se encargarán de hacer memorable una noche de buen surf rock en la que además contarán con una DJ session de vinilos a cargo de David Makingtime como complemento perfecto de la velada que huele a salitre y a amplificadores de válvulas.',
  28.470601, -16.247554,
  'Lone Star, Lone Star',
  'music',
  '2026-06-06 18:00:00+00',
  '2026-06-06 20:00:00+00',
  team_id, 'upcoming', 'lagenda:42368', ARRAY['https://s3-eu-west-1.amazonaws.com/beta.lagenda/programacion/aranas-del-neptuno.jpg']::text[]
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['music'])
  FROM events WHERE external_id = 'lagenda:42368'
ON CONFLICT DO NOTHING;

-- Fotosíntesis - FICMEC 2026 [lagenda:42138]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id, photos) VALUES (
  gen_random_uuid(),
  'Fotosíntesis - FICMEC 2026',
  'Fotosíntesis refuerza así su papel dentro de FICMEC como un espacio de reflexión y aprendizaje en torno a una agricultura más resiliente, consciente y comprometida con el futuro del territorio.',
  28.366453, -16.721122,
  'Icod, Icod',
  'culture',
  '2026-06-06 18:00:00+00',
  '2026-06-06 20:00:00+00',
  team_id, 'upcoming', 'lagenda:42138', ARRAY['https://s3-eu-west-1.amazonaws.com/beta.lagenda/images/jeg-tror-vi-starter-som-lys-still-3.jpg']::text[]
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['culture'])
  FROM events WHERE external_id = 'lagenda:42138'
ON CONFLICT DO NOTHING;

-- ''Hortus Hesperidum'' [lagenda:42406]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id, photos) VALUES (
  gen_random_uuid(),
  '''Hortus Hesperidum''',
  '''Hortus Hesperidum'' es un proyecto personal en torno al mito del Jardín de las Hespéride a cargo de Manolo Yanes que cuenta con la colaboración de 19 artistas de las Islas Canarias. Estas aportaciones provienen además de otras disciplinas artísticas como literatura, escultura, literatura, música y vídeoarte.',
  28.291600, -16.629100,
  'Museo de la Naturaleza y Arqueología, Museo de la Naturaleza y Arqueología',
  'art',
  '2026-06-06 18:00:00+00',
  '2026-06-06 20:00:00+00',
  team_id, 'upcoming', 'lagenda:42406', ARRAY['https://s3-eu-west-1.amazonaws.com/beta.lagenda/programacion/hortus-hesperidum.jpg']::text[]
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['art'])
  FROM events WHERE external_id = 'lagenda:42406'
ON CONFLICT DO NOTHING;

-- ''La cajita de latón'' [lagenda:42150]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id, photos) VALUES (
  gen_random_uuid(),
  '''La cajita de latón''',
  'María Rosa Alonso, se prepara para partir de Canarias a Venezuela, después de sufrir una dura injusticia en su puesto de trabajo en la universidad. preocupados por ella la visitan en un intento fallido por hacer que se quede en la isla. Una pieza que recoge la importancia que posee la amistad en la vida y cómo puede permanecer a través del tiempo y la distancia.',
  28.291600, -16.629100,
  'Zálatta Espacio Escénico, Zálatta Espacio Escénico',
  'culture',
  '2026-06-06 18:00:00+00',
  '2026-06-06 20:00:00+00',
  team_id, 'upcoming', 'lagenda:42150', ARRAY['https://s3-eu-west-1.amazonaws.com/beta.lagenda/programacion/la-cajita-de-laton.jpg']::text[]
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['art'])
  FROM events WHERE external_id = 'lagenda:42150'
ON CONFLICT DO NOTHING;

-- Alex Janssen Quartet [lagenda:42165]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id, photos) VALUES (
  gen_random_uuid(),
  'Alex Janssen Quartet',
  'Alex Janssen, guitarrista de Jazz uruguayo afincado en Canarias desde 1993, desarrolla una intensa actividad musical, participando en una infinidad de proyectos que lo llevan a tocar tanto en las Islas como en el continente.',
  28.291600, -16.629100,
  'Asociación Cultural Equipo PARA, Asociación Cultural Equipo PARA',
  'music',
  '2026-06-06 18:00:00+00',
  '2026-06-06 20:00:00+00',
  team_id, 'upcoming', 'lagenda:42165', ARRAY['https://s3-eu-west-1.amazonaws.com/beta.lagenda/programacion/equipopara.jpg']::text[]
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['music'])
  FROM events WHERE external_id = 'lagenda:42165'
ON CONFLICT DO NOTHING;

-- ‘Dar presencia: Cuerpos ocupando el archivo’ [lagenda:42419]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id, photos) VALUES (
  gen_random_uuid(),
  '‘Dar presencia: Cuerpos ocupando el archivo’',
  'Partiendo de la idea de que conservar sin cuestionar puede perpetuar silencios históricos, este taller de Teresa Correa propone una mirada activa que busca trascender la visita contemplativa a través de una vista guiada compartida entre TEA Tenerife Espacio de las Artes y el MUNA Museo de Naturaleza y Arqueología.',
  28.291600, -16.629100,
  'TEA Tenerife Espacio de las Artes, TEA Tenerife Espacio de las Artes',
  'art',
  '2026-06-06 18:00:00+00',
  '2026-06-06 20:00:00+00',
  team_id, 'upcoming', 'lagenda:42419', ARRAY['https://s3-eu-west-1.amazonaws.com/beta.lagenda/programacion/taller-teresa-correa-tea-tenerife-2026.jpg']::text[]
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['art'])
  FROM events WHERE external_id = 'lagenda:42419'
ON CONFLICT DO NOTHING;

-- Encuentro parrandero [lagenda:42253]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id, photos) VALUES (
  gen_random_uuid(),
  'Encuentro parrandero',
  'II Encuentro Parrandero de Mayores de Garachico y una merienda comunitaria, para compartir canciones, tradiciones y buenos momentos en comunidad.',
  40.946454, -4.117123,
  'Antiguo Convento de San Francisco, Antiguo Convento de San Francisco',
  'music',
  '2026-06-06 18:00:00+00',
  '2026-06-06 20:00:00+00',
  team_id, 'upcoming', 'lagenda:42253', ARRAY['https://s3-eu-west-1.amazonaws.com/beta.lagenda/programacion/parranda-garachico.jpg']::text[]
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['music'])
  FROM events WHERE external_id = 'lagenda:42253'
ON CONFLICT DO NOTHING;

-- UPRISING - Muse Tributo [lagenda:41602]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id, photos) VALUES (
  gen_random_uuid(),
  'UPRISING - Muse Tributo',
  'UPRISING realizaran un extenso repaso a los temas más representativos de la discografía de los británicos, con un espectáculo audiovisual que ya acumula excelentes críticas en las diversas giras nacionales que los albaceteños han llevado a cabo.',
  28.291600, -16.629100,
  'Aguere Espacio Cultural, Aguere Espacio Cultural',
  'music',
  '2026-06-06 18:00:00+00',
  '2026-06-06 20:00:00+00',
  team_id, 'upcoming', 'lagenda:41602', ARRAY['https://s3-eu-west-1.amazonaws.com/beta.lagenda/programacion/uprising_muse_tributo.jpg']::text[]
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['music'])
  FROM events WHERE external_id = 'lagenda:41602'
ON CONFLICT DO NOTHING;

-- Marta Klimasara - FMUC 2026 [lagenda:41695]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id, photos) VALUES (
  gen_random_uuid(),
  'Marta Klimasara - FMUC 2026',
  'El Festival de Música Contemporánea de Tenerife (FMUC), edición 2026, programa un concierto a cargo de la prestigiosa percusionista Marta Klimasara, acompañada por  Andrea Domínguez, María Vera y Verónica Cagigao',
  28.456074, -16.251243,
  'Auditorio de Tenerife Adán Martín, Auditorio de Tenerife Adán Martín',
  'culture',
  '2026-06-06 18:00:00+00',
  '2026-06-06 20:00:00+00',
  team_id, 'upcoming', 'lagenda:41695', ARRAY['https://s3-eu-west-1.amazonaws.com/beta.lagenda/programacion/fmuc-2026.jpg']::text[]
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['culture'])
  FROM events WHERE external_id = 'lagenda:41695'
ON CONFLICT DO NOTHING;

-- Julia Rodríguez [lagenda:42305]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id, photos) VALUES (
  gen_random_uuid(),
  'Julia Rodríguez',
  'Concierto de Julia Rodríguez enmarcado en el programa ‘Cultura y raíces’ del Gobierno de Canarias.  Su primer EP ‘Hacia la vida’, fue seleccionado como mejor disco de músicas de raíz en los Premios Canarios de la Música en 2025. Con este ha recorrido las 8 islas, compartiendo su inconfundible sensibilidad y fuerza.',
  41.128143, 1.206468,
  'Espacio La Granja, Espacio La Granja',
  'culture',
  '2026-06-06 18:00:00+00',
  '2026-06-06 20:00:00+00',
  team_id, 'upcoming', 'lagenda:42305', ARRAY['https://s3-eu-west-1.amazonaws.com/beta.lagenda/programacion/julia_rodriguez_1.jpg']::text[]
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['culture', 'dance'])
  FROM events WHERE external_id = 'lagenda:42305'
ON CONFLICT DO NOTHING;

-- ''Minor Inter Partes'' [lagenda:42323]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id, photos) VALUES (
  gen_random_uuid(),
  '''Minor Inter Partes''',
  '''Minor inter partes'' es la segunda parte de la trilogía que se inició con ''Baleiro'' y, en cierto modo, sucede después. Vaciados los símbolos y sus significados, vaciados los discursos y los relatos el público acompañará a Ensalle y Juan Navarro a la “trastienda” de aquel plató cutre de televisión, al backstage de aquel “reality fake”.',
  39.958949, -4.832246,
  'Teatro Victoria, Teatro Victoria',
  'culture',
  '2026-06-06 18:00:00+00',
  '2026-06-06 20:00:00+00',
  team_id, 'upcoming', 'lagenda:42323', ARRAY['https://s3-eu-west-1.amazonaws.com/beta.lagenda/programacion/minorinterpartes-ensalle.jpg']::text[]
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['art'])
  FROM events WHERE external_id = 'lagenda:42323'
ON CONFLICT DO NOTHING;

-- Rod & Tina [lagenda:41731]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id, photos) VALUES (
  gen_random_uuid(),
  'Rod & Tina',
  'Rod and the Facez y Tina Forever. Dos espléndidos tributos a Rod Stewart y Tina Turner con los grandes éxitos de estas inolvidables leyendas de la música universal',
  28.291600, -16.629100,
  'Auditorio Infanta Leonor, Auditorio Infanta Leonor',
  'culture',
  '2026-06-06 18:00:00+00',
  '2026-06-06 20:00:00+00',
  team_id, 'upcoming', 'lagenda:41731', ARRAY['https://s3-eu-west-1.amazonaws.com/beta.lagenda/programacion/rod-tina.jpg']::text[]
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['culture', 'dance'])
  FROM events WHERE external_id = 'lagenda:41731'
ON CONFLICT DO NOTHING;

-- Cajón Desastre - Adri & Rod [lagenda:41757]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id, photos) VALUES (
  gen_random_uuid(),
  'Cajón Desastre - Adri & Rod',
  'Un show divertido, afilado y único. Anécdotas del público que se convierten en historias improvisadas, escenas envueltas por la música en vivo del DJ improvisador MVBA, y ese equilibrio brillante entre el humor, la empatía y la locura más canalla.',
  28.291600, -16.629100,
  'Café Teatro Rayuela, Café Teatro Rayuela',
  'culture',
  '2026-06-06 18:00:00+00',
  '2026-06-06 20:00:00+00',
  team_id, 'upcoming', 'lagenda:41757', ARRAY['https://s3-eu-west-1.amazonaws.com/beta.lagenda/programacion/cajon_desastre_adri_y_rod_0.jpg']::text[]
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['art'])
  FROM events WHERE external_id = 'lagenda:41757'
ON CONFLICT DO NOTHING;

-- Elton John - Tribute Show [lagenda:41771]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id, photos) VALUES (
  gen_random_uuid(),
  'Elton John - Tribute Show',
  'Experimenta en vivo todos los grandes éxitos de Elton John con este espectacular homenaje al icónico artista británico. Música en vivo, interpretación fiel al artista original y espectaculares juegos de luces.',
  28.291600, -16.629100,
  'Sala Timanfaya, Sala Timanfaya',
  'music',
  '2026-06-06 18:00:00+00',
  '2026-06-06 20:00:00+00',
  team_id, 'upcoming', 'lagenda:41771', ARRAY['https://s3-eu-west-1.amazonaws.com/beta.lagenda/programacion/elton_john_tributo.jpg']::text[]
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['music'])
  FROM events WHERE external_id = 'lagenda:41771'
ON CONFLICT DO NOTHING;

-- Fiestas del Corpus Christi La Orotava 2026 [lagenda:42339]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id, photos) VALUES (
  gen_random_uuid(),
  'Fiestas del Corpus Christi La Orotava 2026',
  'Las celebraciones incluyen confección de alfombras, eucaristías y procesiones del Corpus en varias parroquias, junto a concursos de arrastre, rutas históricas y exposiciones. Se suman recitales, conciertos, elección de la Romera Mayor y actividades en el Liceo de Taoro, además de la Fiesta de los Vinos y el Festival Parrandero.',
  28.389883, -16.523569,
  'La Orotava, La Orotava',
  'culture',
  '2026-06-06 18:00:00+00',
  '2026-06-06 20:00:00+00',
  team_id, 'upcoming', 'lagenda:42339', ARRAY['https://s3-eu-west-1.amazonaws.com/beta.lagenda/programacion/orotava_0.jpg']::text[]
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['culture', 'dance'])
  FROM events WHERE external_id = 'lagenda:42339'
ON CONFLICT DO NOTHING;

-- Ruta de las alfombras - La Orotava [lagenda:41932]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id, photos) VALUES (
  gen_random_uuid(),
  'Ruta de las alfombras - La Orotava',
  'José Maza te guía por la Ruta de Las Alfombras en La Orotava durante varias jornadas en esta propuesta dirigida a todos los públicos',
  28.389883, -16.523569,
  'La Orotava, La Orotava',
  'art',
  '2026-06-06 18:00:00+00',
  '2026-06-06 20:00:00+00',
  team_id, 'upcoming', 'lagenda:41932', ARRAY['https://s3-eu-west-1.amazonaws.com/beta.lagenda/programacion/ruta-alfombras-2026.jpg']::text[]
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['art'])
  FROM events WHERE external_id = 'lagenda:41932'
ON CONFLICT DO NOTHING;

-- Alfombra Joven - Corpus Christi 2026 [lagenda:41954]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id, photos) VALUES (
  gen_random_uuid(),
  'Alfombra Joven - Corpus Christi 2026',
  'Los y las jóvenes del municipio podrán participar en la elaboración de la alfombra joven con motivo del Corpus Christi, una tradición muy arraigada en nuestra localidad.',
  28.139440, -16.739456,
  'Adeje, Adeje',
  'culture',
  '2026-06-06 18:00:00+00',
  '2026-06-06 20:00:00+00',
  team_id, 'upcoming', 'lagenda:41954', ARRAY['https://s3-eu-west-1.amazonaws.com/beta.lagenda/programacion/alfombra_joven_corpus_christi_2026.jpg']::text[]
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['culture', 'dance'])
  FROM events WHERE external_id = 'lagenda:41954'
ON CONFLICT DO NOTHING;

-- Fimucité20 [lagenda:42344]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id, photos) VALUES (
  gen_random_uuid(),
  'Fimucité20',
  'Vigésimo aniversario de Fimucité que incluirá grandes conciertos y una programación dedicada a la música de cine de todos los tiempos con invitados de excepción y homenajes',
  28.293578, -16.621447,
  'Tenerife, Tenerife',
  'music',
  '2026-06-06 18:00:00+00',
  '2026-06-06 20:00:00+00',
  team_id, 'upcoming', 'lagenda:42344', ARRAY['https://s3-eu-west-1.amazonaws.com/beta.lagenda/programacion/fimucite20.jpg']::text[]
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['music'])
  FROM events WHERE external_id = 'lagenda:42344'
ON CONFLICT DO NOTHING;

-- Saoko 2026 [lagenda:42039]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id, photos) VALUES (
  gen_random_uuid(),
  'Saoko 2026',
  'La programación musical incluirá los directos de Abhir y Lewis Potter, junto con las sesiones de los DJs Bumbum, Laureano y Kiddo. Saoko music festival refuerza su apuesta por una experiencia global que integra escenografía temática, espacios visuales y diferentes elementos sorpresa.',
  28.448286, -16.295212,
  'El Polvorín - Taco, El Polvorín - Taco',
  'culture',
  '2026-06-06 18:00:00+00',
  '2026-06-06 20:00:00+00',
  team_id, 'upcoming', 'lagenda:42039', ARRAY['https://s3-eu-west-1.amazonaws.com/beta.lagenda/images/saoko-fest.jpg']::text[]
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['culture', 'dance'])
  FROM events WHERE external_id = 'lagenda:42039'
ON CONFLICT DO NOTHING;

-- Aarón Gómez & Guacimara Gil [lagenda:42350]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id, photos) VALUES (
  gen_random_uuid(),
  'Aarón Gómez & Guacimara Gil',
  'Dos amigos, dos locos del humor, se suben al escenario para compartir risas como solo ellos saben hacer. Aarón Gómez, con una carrera consolidada como uno de los cómicos más queridos de Canarias, y Guacimara Gil, actriz e improvisadora sin límites, se unen para ofrecer una noche inolvidable',
  28.485771, -16.315942,
  'La Laguna, La Laguna',
  'culture',
  '2026-06-06 18:00:00+00',
  '2026-06-06 20:00:00+00',
  team_id, 'upcoming', 'lagenda:42350', ARRAY['https://s3-eu-west-1.amazonaws.com/beta.lagenda/programacion/aaron-gomez-guacimara-gil.jpg']::text[]
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['art'])
  FROM events WHERE external_id = 'lagenda:42350'
ON CONFLICT DO NOTHING;

-- Feria Agroecológica FICMEC 2026 [lagenda:42069]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id, photos) VALUES (
  gen_random_uuid(),
  'Feria Agroecológica FICMEC 2026',
  'El Festival Internacional de Cine Medioambiental de Canarias (FICMEC) reafirma en 2026 su apuesta por lasoberanía alimentaria y el consumo consciente con la celebración de una nueva edición de su Feriade productos agroecológicos y de sostenibilidad.',
  28.372986, -16.764074,
  'Municipio de Garachico, Municipio de Garachico',
  'culture',
  '2026-06-06 18:00:00+00',
  '2026-06-06 20:00:00+00',
  team_id, 'upcoming', 'lagenda:42069', ARRAY['https://s3-eu-west-1.amazonaws.com/beta.lagenda/programacion/agor-ficmec-2026.jpg']::text[]
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['culture'])
  FROM events WHERE external_id = 'lagenda:42069'
ON CONFLICT DO NOTHING;

-- 44ª Fiesta de la Bicicleta - Santa Cruz de Tenerife 2026 [lagenda:42125]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id, photos) VALUES (
  gen_random_uuid(),
  '44ª Fiesta de la Bicicleta - Santa Cruz de Tenerife 2026',
  'La cita volverá a reunir a miles de personas en torno a la movilidad sostenible, la práctica deportiva y la convivencia ciudadana, con una programación que incluye actividades infantiles, talleres educativos y la tradicional bicicletada popular',
  28.467178, -16.250784,
  'Santa Cruz, Santa Cruz',
  'outdoor',
  '2026-06-07 18:00:00+00',
  '2026-06-07 20:00:00+00',
  team_id, 'upcoming', 'lagenda:42125', ARRAY['https://s3-eu-west-1.amazonaws.com/beta.lagenda/programacion/44a-fiesta-de-la-bicicleta-santa-cruz-de-tenerife-2026.jpg']::text[]
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['outdoor', 'sport'])
  FROM events WHERE external_id = 'lagenda:42125'
ON CONFLICT DO NOTHING;

-- Brunch de cine en FICMEC [lagenda:42250]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id, photos) VALUES (
  gen_random_uuid(),
  'Brunch de cine en FICMEC',
  'El restaurante El Rebojo diseñará un menú inspirado en el documental ''Aisha’s Story'', que tendrá su estreno en FICMEC',
  40.946454, -4.117123,
  'Antiguo Convento de San Francisco, Antiguo Convento de San Francisco',
  'culture',
  '2026-06-07 18:00:00+00',
  '2026-06-07 20:00:00+00',
  team_id, 'upcoming', 'lagenda:42250', ARRAY['https://s3-eu-west-1.amazonaws.com/beta.lagenda/images/ficmec-2026.jpg']::text[]
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['art'])
  FROM events WHERE external_id = 'lagenda:42250'
ON CONFLICT DO NOTHING;

-- Primavera Musical 2026 [lagenda:40743]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id, photos) VALUES (
  gen_random_uuid(),
  'Primavera Musical 2026',
  'Primavera Musical es un ciclo de conciertos promovidos por la Federación Tinerfeña de Bandas de Música, que cuenta con la colaboración del Cabildo y que se celebra en el Auditorio de Tenerife entre los meses de marzo y junio.',
  28.456074, -16.251243,
  'Auditorio de Tenerife Adán Martín, Auditorio de Tenerife Adán Martín',
  'music',
  '2026-06-07 18:00:00+00',
  '2026-06-07 20:00:00+00',
  team_id, 'upcoming', 'lagenda:40743', ARRAY['https://s3-eu-west-1.amazonaws.com/beta.lagenda/programacion/la_primavera_musical.jpg']::text[]
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['music'])
  FROM events WHERE external_id = 'lagenda:40743'
ON CONFLICT DO NOTHING;

-- Besay Pérez [lagenda:41673]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id, photos) VALUES (
  gen_random_uuid(),
  'Besay Pérez',
  'Besay Pérez regresa con su ya tradicional concierto ''A la luz de las velas'', acompañado por el piano de Diego Expósito y en esta ocasión junto a una banda formada expresamente para este concierto.',
  28.489700, -16.318123,
  'Teatro Leal, Teatro Leal',
  'culture',
  '2026-06-07 18:00:00+00',
  '2026-06-07 20:00:00+00',
  team_id, 'upcoming', 'lagenda:41673', ARRAY['https://s3-eu-west-1.amazonaws.com/beta.lagenda/programacion/besay_perez.jpg']::text[]
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['culture', 'dance'])
  FROM events WHERE external_id = 'lagenda:41673'
ON CONFLICT DO NOTHING;

-- Marianna Bednarska - FMUC 2026 [lagenda:41696]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id, photos) VALUES (
  gen_random_uuid(),
  'Marianna Bednarska - FMUC 2026',
  'El Festival de Música Contemporánea de Tenerife (FMUC), edición 2026, programa un concierto de la joven percusionista polaca Marianna Bednarska. La artista mantiene una activa actividad artística, no solo como solista, sino también como intérprete de música de cámara, músico de orquesta y profesora de percusión',
  28.456074, -16.251243,
  'Auditorio de Tenerife Adán Martín, Auditorio de Tenerife Adán Martín',
  'culture',
  '2026-06-07 18:00:00+00',
  '2026-06-07 20:00:00+00',
  team_id, 'upcoming', 'lagenda:41696', ARRAY['https://s3-eu-west-1.amazonaws.com/beta.lagenda/programacion/fmuc-2026.jpg']::text[]
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['culture'])
  FROM events WHERE external_id = 'lagenda:41696'
ON CONFLICT DO NOTHING;

-- ''Elara, un viaje a las estrellas'' [lagenda:42306]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id, photos) VALUES (
  gen_random_uuid(),
  '''Elara, un viaje a las estrellas''',
  'Mar Mar Teatro ofrece un viaje hacia la aceptación, el aprendizaje y el crecimiento emocional. La pieza forma parte de la línea familiar La Granja, ¡menudo espacio!',
  41.128143, 1.206468,
  'Espacio La Granja, Espacio La Granja',
  'culture',
  '2026-06-07 18:00:00+00',
  '2026-06-07 20:00:00+00',
  team_id, 'upcoming', 'lagenda:42306', ARRAY['https://s3-eu-west-1.amazonaws.com/beta.lagenda/programacion/elara-mar-mar-teatro.jpg']::text[]
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['art'])
  FROM events WHERE external_id = 'lagenda:42306'
ON CONFLICT DO NOTHING;

-- ''Peligro Narcisista'' [lagenda:42327]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id, photos) VALUES (
  gen_random_uuid(),
  '''Peligro Narcisista''',
  'Espectáculo híbrido entre teatro y psicología, donde Andrés Vernazza interpreta a un narcisista y, junto al público, recrea las siete etapas del vínculo traumático: desde el bombardeo de amor hasta el control emocional.',
  28.291600, -16.629100,
  'Café Teatro Rayuela, Café Teatro Rayuela',
  'culture',
  '2026-06-07 18:00:00+00',
  '2026-06-07 20:00:00+00',
  team_id, 'upcoming', 'lagenda:42327', ARRAY['https://s3-eu-west-1.amazonaws.com/beta.lagenda/programacion/andres-vernazza.jpg']::text[]
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['art'])
  FROM events WHERE external_id = 'lagenda:42327'
ON CONFLICT DO NOTHING;

-- Cuentos que canté por la diversidad [lagenda:42014]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id, photos) VALUES (
  gen_random_uuid(),
  'Cuentos que canté por la diversidad',
  'Concierto lleno de música, juegos y diversión para pequeños y mayores. Un espectáculo vibrante donde la imaginación cobra vida, los ritmos contagian alegría y cada canción invita a cantar, bailar y compartir momentos inolvidables.',
  28.387954, -16.585751,
  'Teatro Cine Los Realejos, Teatro Cine Los Realejos',
  'culture',
  '2026-06-07 18:00:00+00',
  '2026-06-07 20:00:00+00',
  team_id, 'upcoming', 'lagenda:42014', ARRAY['https://s3-eu-west-1.amazonaws.com/beta.lagenda/programacion/ali-wakhanda.jpg']::text[]
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['culture', 'dance'])
  FROM events WHERE external_id = 'lagenda:42014'
ON CONFLICT DO NOTHING;

-- Ballet Stars Gala [lagenda:42361]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id, photos) VALUES (
  gen_random_uuid(),
  'Ballet Stars Gala',
  'En esta noche mágica, se podrá disfrutar de los más impresionantes solos de algunos de los ballets más queridos de todos los tiempos; ''El Lago de los Cisnes'', ''Don Quijote'', ''Raymonda'' o ''El Corsario'', entre otros. Una oportunidad única de disfrutar del ballet clásico en su máxima expresión.',
  36.717993, -4.488701,
  'Paraninfo, Paraninfo',
  'culture',
  '2026-06-07 18:00:00+00',
  '2026-06-07 20:00:00+00',
  team_id, 'upcoming', 'lagenda:42361', ARRAY['https://s3-eu-west-1.amazonaws.com/beta.lagenda/programacion/ballet-stars-gala.jpg']::text[]
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['art'])
  FROM events WHERE external_id = 'lagenda:42361'
ON CONFLICT DO NOTHING;

-- XVII Muestra de alumnos de Timaginas Teatro [lagenda:42394]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id, photos) VALUES (
  gen_random_uuid(),
  'XVII Muestra de alumnos de Timaginas Teatro',
  'Con el teatro sí se juega. ''España en verso'', ''Tiempo de 98'', ''Te pillé Caperucita'', ''Aladín'', ''Rey León'', ''Las comedias de Plauto'', ''La venganza de Don Mendo'', ''Mary Poppins'', ''Bella y Bestia'', ''Mamma mia'', ''La dama boba''. El alumnado de Timaginas Teatro propone grandes propuestas escénicas durante 4 días consecutivos en La Laguna',
  28.489700, -16.318123,
  'Teatro Leal, Teatro Leal',
  'culture',
  '2026-06-08 18:00:00+00',
  '2026-06-08 20:00:00+00',
  team_id, 'upcoming', 'lagenda:42394', ARRAY['https://s3-eu-west-1.amazonaws.com/beta.lagenda/programacion/teatro_leal-1.jpg']::text[]
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['art'])
  FROM events WHERE external_id = 'lagenda:42394'
ON CONFLICT DO NOTHING;

-- Secretos de Familia - II Feria del Pollo de Adeje [lagenda:42423]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id, photos) VALUES (
  gen_random_uuid(),
  'Secretos de Familia - II Feria del Pollo de Adeje',
  'Josefa Dorante desvelará los trucos detrás de su famoso pollo con mojo, una receta cargada de tradición y emoción gastronómica. Una actividad enmarcada en los actos de la II Feria del Pollo de Adeje',
  28.122200, -16.727000,
  'Centro de Desarrollo Turístico de Costa Adeje, Centro de Desarrollo Turístico de Costa Adeje',
  'culture',
  '2026-06-09 18:00:00+00',
  '2026-06-09 20:00:00+00',
  team_id, 'upcoming', 'lagenda:42423', ARRAY['https://s3-eu-west-1.amazonaws.com/beta.lagenda/programacion/fpa26-secretos-familia.jpg']::text[]
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['culture'])
  FROM events WHERE external_id = 'lagenda:42423'
ON CONFLICT DO NOTHING;

-- ''Sabor a Campo'' y ''Aprendiendo Nuestras Tradiciones: Cuadros de Semillas'' [lagenda:2026]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id, photos) VALUES (
  gen_random_uuid(),
  '''Sabor a Campo'' y ''Aprendiendo Nuestras Tradiciones: Cuadros de Semillas''',
  'Inauguración de las Exposiciones ''Sabor a Campo'', realizada por el Mait de Tenerife, y ''Aprendiendo Nuestras Tradiciones: Cuadros de Semillas'' realizada por los alumnos del citado taller.',
  28.291600, -16.629100,
  'Convento Franciscano San Luis Obispo, Convento Franciscano San Luis Obispo',
  'art',
  '2026-06-28 18:00:00+00',
  '2026-06-28 20:00:00+00',
  team_id, 'upcoming', 'lagenda:2026', ARRAY['https://s3-eu-west-1.amazonaws.com/beta.lagenda/programacion/sabor_a_campo.jpg']::text[]
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['art'])
  FROM events WHERE external_id = 'lagenda:2026'
ON CONFLICT DO NOTHING;

-- ''Notas al pie'' [lagenda:41518]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id, photos) VALUES (
  gen_random_uuid(),
  '''Notas al pie''',
  'El museo TEA Tenerife Espacio de las Artes inaugura la exposición ''Notas al pie'', el nuevo proyecto de Cabello/Carceller (Helena Cabello, París, 1963/Carceller, Madrid, 1964), que propone releer la historia desde sus márgenes, poniendo el foco en aquello que quedó fuera del relato oficial.',
  28.291600, -16.629100,
  'TEA Tenerife Espacio de las Artes, TEA Tenerife Espacio de las Artes',
  'art',
  '2026-07-05 18:00:00+00',
  '2026-07-05 20:00:00+00',
  team_id, 'upcoming', 'lagenda:41518', ARRAY['https://s3-eu-west-1.amazonaws.com/beta.lagenda/programacion/vivian-deniz.jpg']::text[]
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['art'])
  FROM events WHERE external_id = 'lagenda:41518'
ON CONFLICT DO NOTHING;

-- ''Sobre la carne, en el vacío'' [lagenda:41614]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id, photos) VALUES (
  gen_random_uuid(),
  '''Sobre la carne, en el vacío''',
  'El trabajo de este creador emergente propone entender la pintura no como una superficie estática, sino como un organismo en constante tensión entre lo físico y lo conceptual.',
  28.291600, -16.629100,
  'Sala  Arte Contemporáneo del Gobierno de Canarias, Sala  Arte Contemporáneo del Gobierno de Canarias',
  'art',
  '2026-06-26 18:00:00+00',
  '2026-06-26 20:00:00+00',
  team_id, 'upcoming', 'lagenda:41614', ARRAY['https://s3-eu-west-1.amazonaws.com/beta.lagenda/images/tempus_edax_rerum.jpeg']::text[]
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['art'])
  FROM events WHERE external_id = 'lagenda:41614'
ON CONFLICT DO NOTHING;

-- ''Marine Lucid Dream'' [lagenda:41781]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id, photos) VALUES (
  gen_random_uuid(),
  '''Marine Lucid Dream''',
  'Con la presencia del autor y de la comisaria Anna Dimitrova, de Adda Gallery Ibiza. Una colaboración de Espacio Bronzo con Adda Gallery Ibiza.',
  28.291600, -16.629100,
  'Sala de Arte Bronzo, Sala de Arte Bronzo',
  'art',
  '2026-06-26 18:00:00+00',
  '2026-06-26 20:00:00+00',
  team_id, 'upcoming', 'lagenda:41781', ARRAY['https://s3-eu-west-1.amazonaws.com/beta.lagenda/programacion/espacio_bronzo_en_mayo_2026_cartel.jpeg']::text[]
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['art'])
  FROM events WHERE external_id = 'lagenda:41781'
ON CONFLICT DO NOTHING;

-- Visitas al Templo Masónico de Santa Cruz de Tenerife [lagenda:39575]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id, photos) VALUES (
  gen_random_uuid(),
  'Visitas al Templo Masónico de Santa Cruz de Tenerife',
  'El Templo Masónico de Santa Cruz de Tenerife acoge visitas libres y guiadas tras un proceso integral de rehabilitación orientado a su conservación y puesta en valor',
  28.467178, -16.250784,
  'Santa Cruz, Santa Cruz',
  'art',
  '2026-11-01 19:00:00+00',
  '2026-11-01 21:00:00+00',
  team_id, 'upcoming', 'lagenda:39575', ARRAY['https://s3-eu-west-1.amazonaws.com/beta.lagenda/insert_images/templo-masonico-tenerife.jpg']::text[]
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['art'])
  FROM events WHERE external_id = 'lagenda:39575'
ON CONFLICT DO NOTHING;

-- ''Sombras y poemas'' [lagenda:40148]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id, photos) VALUES (
  gen_random_uuid(),
  '''Sombras y poemas''',
  '''Sombras y poemas'', del escultor barcelonés Jaume Plensa expone  una muestra que reúne cerca de un centenar de obras, un recorrido artístico que aborda temas como la identidad, la espiritualidad, el lenguaje y la introspección a través de esculturas.',
  28.463600, -16.251800,
  'Espacio Cultural CajaCanarias Santa Cruz, Espacio Cultural CajaCanarias Santa Cruz',
  'art',
  '2026-06-13 18:00:00+00',
  '2026-06-13 20:00:00+00',
  team_id, 'upcoming', 'lagenda:40148', ARRAY['https://s3-eu-west-1.amazonaws.com/beta.lagenda/images/sin-titulo-3_4.jpg']::text[]
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['art'])
  FROM events WHERE external_id = 'lagenda:40148'
ON CONFLICT DO NOTHING;

-- Murales en los Cristianos [lagenda:40394]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id, photos) VALUES (
  gen_random_uuid(),
  'Murales en los Cristianos',
  'Creación de muestras artísticas permanentes que contribuyen a mejorar la estética urbana y a poner en valor las tradiciones del municipio.',
  28.052969, -16.713820,
  'Centro Cultural Los Cristianos, Centro Cultural Los Cristianos',
  'art',
  '2026-12-31 19:00:00+00',
  '2026-12-31 21:00:00+00',
  team_id, 'upcoming', 'lagenda:40394', ARRAY['https://s3-eu-west-1.amazonaws.com/beta.lagenda/programacion/murales-de-los-cristinos.jpg']::text[]
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['art'])
  FROM events WHERE external_id = 'lagenda:40394'
ON CONFLICT DO NOTHING;

-- ''Estancias Imaginadas III'' [lagenda:40499]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id, photos) VALUES (
  gen_random_uuid(),
  '''Estancias Imaginadas III''',
  'Tercera muestra permanente del museo LM Arte Colección con el título Estancias Imaginadas III.  La muestra propone un recorrido por la historia de la casa a través de sus estancias, estableciendo un diálogo entre el patrimonio arquitectónico y una selección de los fondos del museo mediante un imaginario artístico crítico y diverso.',
  28.291600, -16.629100,
  'LM arte colección, LM arte colección',
  'art',
  '2027-12-31 19:00:00+00',
  '2027-12-31 21:00:00+00',
  team_id, 'upcoming', 'lagenda:40499', ARRAY['https://s3-eu-west-1.amazonaws.com/beta.lagenda/programacion/estancias-imaginadas-lm-arte.jpg']::text[]
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['art'])
  FROM events WHERE external_id = 'lagenda:40499'
ON CONFLICT DO NOTHING;

-- ''Alguien recordará al gallotia auritae'' [lagenda:41121]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id, photos) VALUES (
  gen_random_uuid(),
  '''Alguien recordará al gallotia auritae''',
  'El programa Identitaria Canarias impulsa el documental "Los oficios de vivir: tradición y trabajo en los paisajes culturales urbanos de Canarias" sobre diversos oficios tradicionales del archipiélago en su contexto urbano, resaltando su valor cultural, histórico y social.',
  41.883148, 2.243306,
  'Online, Online',
  'art',
  '2026-12-31 19:00:00+00',
  '2026-12-31 21:00:00+00',
  team_id, 'upcoming', 'lagenda:41121', ARRAY['https://s3-eu-west-1.amazonaws.com/beta.lagenda/programacion/rafael_arrocha.jpg']::text[]
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['art'])
  FROM events WHERE external_id = 'lagenda:41121'
ON CONFLICT DO NOTHING;

-- Cándido Camacho ''Ritos del deseo'' [lagenda:41161]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id, photos) VALUES (
  gen_random_uuid(),
  'Cándido Camacho ''Ritos del deseo''',
  'Esta exposición dedicada al artista palmero Cándido Camacho (1951–1992) propone una revisión de su producción y responde a la necesidad de ofrecer una lectura actualizada de la trayectoria de un creador que contribuyó de forma significativa al desarrollo del arte contemporáneo en Canarias, pero que en las últimas décadas ha quedado desplazado hacia los márgenes.',
  28.291600, -16.629100,
  'TEA Tenerife Espacio de las Artes, TEA Tenerife Espacio de las Artes',
  'art',
  '2026-06-14 18:00:00+00',
  '2026-06-14 20:00:00+00',
  team_id, 'upcoming', 'lagenda:41161', ARRAY['https://s3-eu-west-1.amazonaws.com/beta.lagenda/programacion/ritos_del_deseo.jpg']::text[]
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['art'])
  FROM events WHERE external_id = 'lagenda:41161'
ON CONFLICT DO NOTHING;

-- ''Gráfica de la Conca'' [lagenda:41385]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id, photos) VALUES (
  gen_random_uuid(),
  '''Gráfica de la Conca''',
  '''Gráfica de la Conca'' reúne una selección de obra gráfica procedente de los antiguos fondos de la histórica Sala Conca. A través de grabados, litografías, serigrafías, múltiples y libros de artista, la exposición muestra la riqueza técnica y la diversidad de lenguajes que atravesaron aquel tiempo, desde la abstracción y el informalismo hasta la poesía visual y la experimentación conceptual.',
  28.291600, -16.629100,
  'LM arte colección, LM arte colección',
  'art',
  '2026-06-06 18:00:00+00',
  '2026-06-06 20:00:00+00',
  team_id, 'upcoming', 'lagenda:41385', ARRAY['https://s3-eu-west-1.amazonaws.com/beta.lagenda/programacion/grafica-de-la-conca-tenerife-2026.jpg']::text[]
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['art'])
  FROM events WHERE external_id = 'lagenda:41385'
ON CONFLICT DO NOTHING;

-- ''Ramón Gaya. La realidad salvada'' [lagenda:41790]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id, photos) VALUES (
  gen_random_uuid(),
  '''Ramón Gaya. La realidad salvada''',
  'La muestra ''Ramón Gaya. La realidad salvada'',  con un amplio programa de actividades paralelas, ofrece una representativa selección de obras de las diferentes etapas de la trayectoria artística del pintor, realizadas entre 1923 y 2003.',
  28.291600, -16.629100,
  'Fundación Cristino de Vera-Espacio Cultural CajaCanarias, Fundación Cristino de Vera-Espacio Cultural CajaCanarias',
  'art',
  '2026-07-25 18:00:00+00',
  '2026-07-25 20:00:00+00',
  team_id, 'upcoming', 'lagenda:41790', ARRAY['https://s3-eu-west-1.amazonaws.com/beta.lagenda/programacion/ramon-gaya.-la-realidad-salvada.jpg']::text[]
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['art'])
  FROM events WHERE external_id = 'lagenda:41790'
ON CONFLICT DO NOTHING;

-- ''Desapego'' [lagenda:42251]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id, photos) VALUES (
  gen_random_uuid(),
  '''Desapego''',
  'Exposición que habita ese espacio extraño entre lo que soltamos y lo que todavía permanece. A través de la pintura, instalación, fotografía y otros lenguajes contemporáneos, un grupo de jóvenes artistas explora los vínculos con la identidad, la memoria, los objetos y las emociones que nos construyen.',
  28.485798, -16.312900,
  'Convento Santo Domingo La Laguna, Convento Santo Domingo La Laguna',
  'art',
  '2026-06-13 18:00:00+00',
  '2026-06-13 20:00:00+00',
  team_id, 'upcoming', 'lagenda:42251', ARRAY['https://s3-eu-west-1.amazonaws.com/beta.lagenda/programacion/desapego.jpg']::text[]
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['art'])
  FROM events WHERE external_id = 'lagenda:42251'
ON CONFLICT DO NOTHING;

-- ''The not so still life II'' [lagenda:42121]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id, photos) VALUES (
  gen_random_uuid(),
  '''The not so still life II''',
  'Un acto de inauguración de la exposición ''The not so still life II'' de la mano de Celestino Mesa',
  28.291600, -16.629100,
  'Desván Blanco Espacio Cultural, Desván Blanco Espacio Cultural',
  'art',
  '2026-06-12 18:00:00+00',
  '2026-06-12 20:00:00+00',
  team_id, 'upcoming', 'lagenda:42121', ARRAY['https://s3-eu-west-1.amazonaws.com/beta.lagenda/programacion/the-not-so-still-life-exposicion.jpg']::text[]
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['art'])
  FROM events WHERE external_id = 'lagenda:42121'
ON CONFLICT DO NOTHING;

-- ''Sueños'' [lagenda:42268]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id, photos) VALUES (
  gen_random_uuid(),
  '''Sueños''',
  'A través de retratos de personas de distintas edades, procedencias y condiciones vitales, Pedro Pérez Esteban explora el universo emocional y humano que se esconde tras los anhelos individuales.',
  28.465490, -16.250776,
  'La Recova Centro de Arte, La Recova Centro de Arte',
  'culture',
  '2026-06-28 18:00:00+00',
  '2026-06-28 20:00:00+00',
  team_id, 'upcoming', 'lagenda:42268', ARRAY['https://s3-eu-west-1.amazonaws.com/beta.lagenda/programacion/pedro_perez.jpg']::text[]
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['culture'])
  FROM events WHERE external_id = 'lagenda:42268'
ON CONFLICT DO NOTHING;

-- ''Casi Alguien'' [lagenda:42205]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id, photos) VALUES (
  gen_random_uuid(),
  '''Casi Alguien''',
  'Teresa Correa, Pedro González, Moneiba Lemes, Fernando Martín Godoy, Cristina Temes. En esta muestra, el retrato aparece no como una afirmación, sino como una pregunta abierta sobre quiénes somos y cómo nos representamos.',
  28.291600, -16.629100,
  'Bibli, Bibli',
  'art',
  '2026-07-31 18:00:00+00',
  '2026-07-31 20:00:00+00',
  team_id, 'upcoming', 'lagenda:42205', ARRAY['https://s3-eu-west-1.amazonaws.com/beta.lagenda/programacion/casi-alguien_0.jpg']::text[]
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['art'])
  FROM events WHERE external_id = 'lagenda:42205'
ON CONFLICT DO NOTHING;

-- ''Desbordes y tangentes'' [lagenda:42358]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id, photos) VALUES (
  gen_random_uuid(),
  '''Desbordes y tangentes''',
  'La exposición plantea un recorrido por distintas aproximaciones al dibujo contemporáneo, entendido ya no como una práctica limitada al papel y a lo bidimensional, sino como un lenguaje capaz de ocupar el espacio, expandirse hacia lo instalativo, lo performático o lo audiovisual, y dialogar con el cuerpo y la arquitectura.',
  28.100484, -15.416912,
  'Fundación Mapfre Canarias, Fundación Mapfre Canarias',
  'art',
  '2026-07-31 18:00:00+00',
  '2026-07-31 20:00:00+00',
  team_id, 'upcoming', 'lagenda:42358', ARRAY['https://s3-eu-west-1.amazonaws.com/beta.lagenda/programacion/desbordes-y-tangentes-tenerife-mapfre.arte_.jpg']::text[]
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['art'])
  FROM events WHERE external_id = 'lagenda:42358'
ON CONFLICT DO NOTHING;

-- ''Marine Lucid Dream'' [lagenda:42357]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id, photos) VALUES (
  gen_random_uuid(),
  '''Marine Lucid Dream''',
  'Esculturas, dibujos a grafiti y pinturas elaboradas en Tenerife por el autor ucraniano Aleksei Bordusov, conocido internacionalmente como Aec Interesni Kazki. Una exposición sobre la libertad de la conciencia dentro de un mundo que ofrece muy poca de ella.',
  28.291600, -16.629100,
  'Sala de Arte Bronzo, Sala de Arte Bronzo',
  'art',
  '2026-06-26 18:00:00+00',
  '2026-06-26 20:00:00+00',
  team_id, 'upcoming', 'lagenda:42357', ARRAY['https://s3-eu-west-1.amazonaws.com/beta.lagenda/programacion/blossom-bearer-aleksei-bordusov.jpg']::text[]
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['art'])
  FROM events WHERE external_id = 'lagenda:42357'
ON CONFLICT DO NOTHING;

-- ''Donde cantan los pelícanos'' [lagenda:42352]
INSERT INTO events (id, title, description, lat, lng, place_name, category, start_time, end_time, creator_id, status, external_id, photos) VALUES (
  gen_random_uuid(),
  '''Donde cantan los pelícanos''',
  'Instalación de Carlos Nicanor que explora vínculos entre orillas atlánticas mediante islas flotantes y una reflexión crítica sobre la idea de paraíso. El proyecto conecta experiencias migratorias, memoria y territorio. La obra del escultor destaca por su intensidad poética y su investigación sobre formas, procesos y relaciones entre arte y ciudadanía.',
  28.457310, -16.256110,
  'Espacio Cultural El Tanque, Espacio Cultural El Tanque',
  'art',
  '2026-08-10 18:00:00+00',
  '2026-08-10 20:00:00+00',
  team_id, 'upcoming', 'lagenda:42352', ARRAY['https://s3-eu-west-1.amazonaws.com/beta.lagenda/images/donde-cantan-los-pelicanos.jpeg']::text[]
) ON CONFLICT (external_id) DO NOTHING;
INSERT INTO event_tags (event_id, tag)
  SELECT id, unnest(ARRAY['art'])
  FROM events WHERE external_id = 'lagenda:42352'
ON CONFLICT DO NOTHING;

END $$;