import type { MeuweEvent } from './types.ts';

const MEUWE_TEAM_UUID = process.env.MEUWE_TEAM_UUID ?? 'b864b6bf-4282-4644-ab8f-b17b661b7841';

function esc(s: string): string {
  return s.replace(/'/g, "''");
}

// Convert a JS Date (UTC) to Postgres timestamptz literal
function pgTs(d: Date): string {
  return d.toISOString().replace('T', ' ').replace(/\.\d{3}Z$/, '+00');
}

// Postgres text[] literal: '{}' when empty, ARRAY[...]::text[] otherwise
function pgTextArray(arr: string[]): string {
  if (!arr.length) return `'{}'`;
  return `ARRAY[${arr.map(s => `'${esc(s)}'`).join(', ')}]::text[]`;
}

export function generateSql(
  events: MeuweEvent[],
  meta: { dateFrom: string; dateTo: string; generatedAt: string }
): string {
  const lines: string[] = [
    `-- Auto-generated by event-sync on ${meta.generatedAt}`,
    `-- Scraped range: ${meta.dateFrom} → ${meta.dateTo}`,
    `-- Run manually in Supabase Dashboard → SQL Editor`,
    `-- Idempotent: ON CONFLICT (external_id) DO NOTHING skips duplicates`,
    `-- Requires migration 20260530_add_external_id.sql`,
    '',
    `DO $$`,
    `DECLARE`,
    `  team_id uuid := '${MEUWE_TEAM_UUID}';`,
    `BEGIN`,
    '',
  ];

  for (const ev of events) {
    lines.push(`-- ${esc(ev.title)} [${ev.externalId}]`);
    lines.push(
      `INSERT INTO public.events (id, title, description, lat, lng, place_name, ` +
      `category, start_time, end_time, creator_id, status, external_id, photos) VALUES (`
    );
    lines.push(`  gen_random_uuid(),`);
    lines.push(`  '${esc(ev.title)}',`);
    lines.push(`  '${esc(ev.description)}',`);
    lines.push(`  ${ev.lat.toFixed(6)}, ${ev.lng.toFixed(6)},`);
    lines.push(`  '${esc(ev.placeName)}',`);
    lines.push(`  '${ev.category}',`);
    lines.push(`  '${pgTs(ev.startTime)}',`);
    lines.push(`  '${pgTs(ev.endTime)}',`);
    lines.push(`  team_id, 'upcoming', '${esc(ev.externalId)}', ${pgTextArray(ev.photos)}`);
    lines.push(`) ON CONFLICT (external_id) DO NOTHING;`);

    if (ev.tags.length) {
      lines.push(`INSERT INTO public.event_tags (event_id, tag)`);
      lines.push(`  SELECT id, unnest(ARRAY[${ev.tags.map(t => `'${esc(t)}'`).join(', ')}])`);
      lines.push(`  FROM public.events WHERE external_id = '${esc(ev.externalId)}'`);
      lines.push(`ON CONFLICT DO NOTHING;`);
    }

    lines.push('');
  }

  lines.push('END $$;');
  return lines.join('\n');
}
